fragment CollectionExplorerProperties on Collection {
  id
  title
  externalId
  collectionsTags {
    nodes {
      name
    }
  }
  publishedDate
  createdDate
  updatedDate
  publishStatus
  collectionsImages {
    nodes {
      imageId
    }
  }
}

query CollectionRelatedEntities($id: Int!) {
  collections(
    filter: {
      collectionRelations: { some: { movie: { entityId: { equalTo: id } } } }
    }
  ) {
    nodes {
      ...CollectionExplorerProperties
      collectionRelations(orderBy: SORT_ORDER_ASC) {
        nodes {
          movie {
            entityId
            title
            publishStatus
            entityImages: moviesImages {
              nodes {
                imageId
              }
            }
          }
          id
          sortOrder
        }
      }
    }
  }
}
