apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-kv-unifiedstreaming
spec:
  provider:
    azurekv:
      authSecretRef:
        clientId:
          key: ClientId
          name: azure-external-access-service-principal-credentials
        clientSecret:
          key: ClientSecret
          name: azure-external-access-service-principal-credentials
      authType: ServicePrincipal
      environmentType: PublicCloud
      tenantId: db0b4725-608f-4d84-b2e3-7fc15b0cb2d4
      vaultUrl: https://cus-prod-vod2lv-qe7.vault.azure.net
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: key-vault-unifiedstreaming
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: SecretStore
    name: azure-kv-unifiedstreaming
  target:
    name: key-vault-unifiedstreaming
    creationPolicy: Owner
  data:
  - secretKey: usp-license-key
    remoteRef:
      key: secret/usp-license-key
  - secretKey: rabbitmq-connection-string
    remoteRef:
      key: secret/rabbitmq-connection-string
  - secretKey: azurestorageaccountname
    remoteRef:
      key: secret/azurestorageaccountname
  - secretKey: azurestorageaccountkey
    remoteRef:
      key: secret/azurestorageaccountkey
  - secretKey: api-key
    remoteRef:
      key: secret/api-key
