query SeasonsLicense($id: Int!) {
  seasonsLicense(id: $id) {
    seasonsLicensesCountries {
      nodes {
        countryCode
        countryGroupId
        id
      }
    }
    licenseEnd
    licenseStart
    seasonId
    createdDate
    updatedDate
    updatedUser
    createdUser
    isDownloadable
    downloadedAssetLifespan
  }
  allCountryTypes(orderBy: NAME_ASC) {
    nodes {
      name
      id
    }
  }
}

mutation UpdateSeasonsLicense($input: UpdateSeasonsLicenseInput!) {
  updateSeasonsLicense(input: $input) {
    clientMutationId
  }
}

mutation DeleteSeasonsLicense($input: DeleteSeasonsLicenseInput!) {
  deleteSeasonsLicense(input: $input) {
    clientMutationId
  }
}
