query SeasonsLicense($id: Int!) {
  seasonsLicense(id: $id) {
    seasonsLicensesCountries {
      nodes {
        code
      }
    }
    licenseEnd
    licenseStart
    seasonId
    createdDate
    updatedDate
    updatedUser
    createdUser
    isDownloadable
    downloadedAssetLifespan
  }
}

mutation UpdateSeasonsLicense($input: UpdateSeasonsLicenseInput!) {
  updateSeasonsLicense(input: $input) {
    clientMutationId
  }
}

mutation DeleteSeasonsLicense($input: DeleteSeasonsLicenseInput!) {
  deleteSeasonsLicense(input: $input) {
    clientMutationId
  }
}
