query GetCustomerById($customerId: String!) {
  getCustomer(id: $customerId) {
    id
    first_name
    last_name
    email
    gender
    registration_country
  }
}

query GetCustomerEmailById($customerId: String!) {
  getCustomer(id: $customerId) {
    email
  }
}

mutation UpdateCustomer($input: UpdateCustomerInput) {
  updateCustomer(input: $input) {
    id
    first_name
    last_name
    email
    gender
    registration_country
  }
}

mutation DeleteCustomer($Id: String!) {
  deleteCustomer(id: $Id){
    code
    message
  }
}

mutation resetPassword($email: String) {
  resetPassword(email: $email) {
    code
    message
  }
}

mutation resendActivation($email: String) {
  resendActivation(email: $email) {
    code
    message
  }
}
