mutation CreateAxinomServiceConfigEntitlement {
  createAxinomServiceDeploymentManifest(
    input: {
      axinomServiceDeploymentManifest: {
        serviceDefinitionId: "#{serviceDefinitionIdEntitlement}#"
        configMap: {
          serviceId: "ax-entitlement-service"
          version: "1.0"
          dnsMappedPorts: [{ name: "api", port: 11600 }]
          pilets: []
          serviceAccounts: []
          secureVariables: {
            POSTGRESQL_HOST: "${__ax_hosted__.pg.host}"
            POSTGRESQL_PORT: "${__ax_hosted__.pg.port}"
            POSTGRESQL_USER_SUFFIX: "${__ax_hosted__.pg.user_suffix}"
            PGSSLMODE: "${__ax_hosted__.pg.sslmode}"
            DATABASE_NAME: "${__ax_hosted__.pg.database_name}"
            DATABASE_OWNER: "${__ax_hosted__.pg.db_owner_role}"
            DATABASE_OWNER_PASSWORD: "${__ax_hosted__.pg.db_owner_password}"
            DATABASE_LOGIN: "${__ax_hosted__.pg.db_login_role}"
            DATABASE_LOGIN_PASSWORD: "${__ax_hosted__.pg.db_login_password}"
            DATABASE_GQL_ROLE: "${__ax_hosted__.pg.db_gql_role}"
            RABBITMQ_HOST: "${__ax_hosted__.rmq.host}"
            RABBITMQ_PORT: "${__ax_hosted__.rmq.port}"
            RABBITMQ_PROTOCOL: "${__ax_hosted__.rmq.protocol}"
            RABBITMQ_MGMT_HOST: "${__ax_hosted__.rmq.mgmt_host}"
            RABBITMQ_MGMT_PORT: "${__ax_hosted__.rmq.mgmt_port}"
            RABBITMQ_MGMT_PROTOCOL: "${__ax_hosted__.rmq.mgmt_protocol}"
            RABBITMQ_VHOST: "${__ax_hosted__.rmq.vhost}"
            RABBITMQ_USER: "${__ax_hosted__.rmq.username}"
            RABBITMQ_PASSWORD: "${__ax_hosted__.rmq.password}"
            DRM_LICENSE_COMMUNICATION_KEY: "#{drm-license-communication-key}#"
            DRM_LICENSE_COMMUNICATION_KEY_ID: "#{drm-license-communication-key-id}#"
            GEOLITE2_LICENSE_KEY: "DownloadFromStorageAcc-NoLicenseNeeded"
            MAXMIND_ACCOUNT_ID: "DownloadFromStorageAcc-NoMaxmindAccountNeeded"
          }
          regularVariables: {
            SERVICE_ID: "entitlement-service"
            PORT: "${__ax_hosted__.port.api}"
            NODE_ENV: "test"
            LOG_LEVEL: "DEBUG"
            SECURE_LOGGING_MODE: "UNSAFE_DEBUG_UNSAFE"
            GRAPHQL_GUI_ENABLED: true
            TENANT_ID: "${__ax_hosted__.env.tenant_id}"
            ENVIRONMENT_ID: "${__ax_hosted__.env.environment_id}"
            ID_SERVICE_AUTH_BASE_URL: "${__ax_hosted__.svc.ax-id-service.auth_base_url}"
            USER_SERVICE_AUTH_BASE_URL: "${__ax_hosted__.svc.ax-user-service.auth_base_url}"
            CATALOG_SERVICE_BASE_URL: "https://${__ax_hosted__.dns.ax-catalog-service.api}"
            GEOLITE2_DOWNLOAD_URL: "#{geoLite2DownloadUrl}#"
            MAXMIND_ACCOUNT_ID: "-"
            PG_POOL_MAX_CONNECTIONS: "25"
            TRX_DB_SCHEMA: "app_hidden"
            TRX_NEXT_MESSAGES_FUNCTION_SCHEMA: "app_hidden"
            TRX_MESSAGE_PROCESSING_TIMEOUT_IN_MS: 15000
            TRX_NEXT_MESSAGES_LOCK_IN_MS: 15000
            TRX_MAX_ATTEMPTS: 5
            TRX_MAX_POISONOUS_ATTEMPTS: 3
            TRX_MESSAGE_CLEANUP_INTERVAL_IN_MS: 300000
            TRX_MESSAGE_CLEANUP_PROCESSED_IN_SEC: 604800
            TRX_MESSAGE_CLEANUP_ABANDONED_IN_SEC: 1209600
            TRX_MESSAGE_CLEANUP_ALL_IN_SEC: 5184000
            TRX_NEXT_MESSAGES_BATCH_SIZE: 5
            TRX_NEXT_MESSAGES_POLLING_INTERVAL_IN_MS: 500
            TRX_INBOX_DB_TABLE: "inbox"
            TRX_INBOX_NEXT_MESSAGES_FUNCTION_NAME: "next_inbox_messages"
            TRX_INBOX_ENABLE_MAX_ATTEMPTS_PROTECTION: true
            TRX_INBOX_ENABLE_POISONOUS_MESSAGE_PROTECTION: true
          }
        }
      }
    }
  ) {
    clientMutationId
    axinomServiceDeploymentManifest {
      configMap
      id
      serviceDefinitionId
    }
  }
}
