nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - linux
    - darwin

npmMinimalAgeGate: '7d'

packageExtensions:
  "@types/apollo-upload-client@*":
    peerDependencies:
      "@apollo/client": "*"
npmPreapprovedPackages:
  - '@axinom/*'

yarnPath: .yarn/releases/yarn-4.12.0.cjs
