apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml
  - redis-pvc.yaml
  - ../../base
namespace: customizable-cb
patchesStrategicMerge:
  - deployment.yaml
  - http-route.yaml
