--! Message: add-audio-books

-------------- #audio_book --------------
--    _             _  _         ___            _
--   /_\  _  _  __| |(_) ___   | _ ) ___  ___ | |__
--  / _ \| || |/ _` || |/ _ \  | _ \/ _ \/ _ \| / /
-- /_/ \_\\_,_|\__,_||_|\___/  |___/\___/\___/|_\_\
------------------------------------------

-- audio_book_review_status enum
SELECT ax_define.create_enum_table(
  'audio_book_review_status',
  'app_public',
  ':DATABASE_LOGIN',
  '{"PENDING","APPROVED","REJECTED"}',
  '{"Pending","Approved","Rejected"}');

-- table: audio_books
DROP TABLE IF EXISTS app_public.audio_books CASCADE;
CREATE TABLE app_public.audio_books (
  id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title text NOT NULL,
  author text,
  duration_in_seconds integer,
  is_abridged boolean DEFAULT false,

  CONSTRAINT title_max_length CHECK(ax_utils.constraint_max_length(title, 100, 'The title can only be %2$s characters long.')),
  CONSTRAINT title_not_empty CHECK(ax_utils.constraint_not_empty(title, 'The title cannot be empty.'))
);
SELECT ax_define.define_audit_date_fields_on_table('audio_books', 'app_public');
SELECT ax_define.define_audit_user_fields_on_table('audio_books', 'app_public', ':DEFAULT_USERNAME');
SELECT ax_define.set_enum_as_column_type('review_status', 'audio_books', 'app_public', 'audio_book_review_status', 'app_public', 'PENDING');
SELECT ax_define.set_enum_domain('review_status', 'audio_books', 'app_public', 'audio_book_review_status_enum', 'app_public');

GRANT SELECT, DELETE ON app_public.audio_books TO ":DATABASE_GQL_ROLE";
GRANT INSERT (
  title,
  author,
  duration_in_seconds,
  is_abridged
) ON app_public.audio_books TO ":DATABASE_GQL_ROLE";
GRANT UPDATE (
  title,
  author,
  duration_in_seconds,
  is_abridged,
  review_status
) ON app_public.audio_books TO ":DATABASE_GQL_ROLE";

SELECT ax_define.define_indexes_with_id('title', 'audio_books', 'app_public');
SELECT ax_define.define_indexes_with_id('author', 'audio_books', 'app_public');
SELECT ax_define.define_index('review_status', 'audio_books', 'app_public');
SELECT ax_define.define_indexes_with_id('created_date', 'audio_books', 'app_public');
SELECT ax_define.define_indexes_with_id('updated_date', 'audio_books', 'app_public');
SELECT ax_define.define_like_index('title', 'audio_books', 'app_public');
SELECT ax_define.define_like_index('author', 'audio_books', 'app_public');
SELECT ax_define.define_timestamps_trigger('audio_books', 'app_public');
SELECT ax_define.define_users_trigger('audio_books', 'app_public');
SELECT ax_define.define_authentication('AUDIO_BOOK_READER,AUDIO_BOOK_EDITOR,ADMIN', 'AUDIO_BOOK_EDITOR,ADMIN', 'audio_books', 'app_public');

-- table: audio_books_tags
DROP TABLE IF EXISTS app_public.audio_books_tags CASCADE;
CREATE TABLE app_public.audio_books_tags (
  audio_book_id integer NOT NULL REFERENCES app_public.audio_books(id) ON DELETE CASCADE,
  name text NOT NULL,

  PRIMARY KEY(audio_book_id, name),
  CONSTRAINT name_not_empty CHECK(ax_utils.constraint_not_empty(name, 'The name cannot be empty.'))
);

GRANT SELECT, INSERT, UPDATE, DELETE ON app_public.audio_books_tags TO ":DATABASE_GQL_ROLE";

SELECT ax_define.define_index('audio_book_id', 'audio_books_tags', 'app_public');
SELECT ax_define.define_like_index('name', 'audio_books_tags', 'app_public');
SELECT ax_define.live_suggestions_endpoint('name', 'audio_books_tags', 'app_public');
SELECT ax_define.define_authentication('AUDIO_BOOK_READER,AUDIO_BOOK_EDITOR,ADMIN', 'AUDIO_BOOK_EDITOR,ADMIN', 'audio_books_tags', 'app_public');
