apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
spec:
  template:
    spec:
      nodeSelector:
        mosaic.axinom.com/workload_type: customizable-services
        mosaic.axinom.com/hosting_node_pool: basic_balanced_axinom_owned
      tolerations:
        - key: mosaic.axinom.com/customizable-services
          operator: Equal
          value: 'True'
          effect: NoSchedule
      containers:
        - name: app
          env:
            - name: NODE_ENV
              value: production
            - name: LOG_LEVEL
              value: DEBUG
            - name: POSTGRESQL_HOST
              value: mosaic-prod-ubi-customizable-pub.pgm6jr3cwhzp7me4q9fxpm6217.postgres.ubicloud.com
            - name: POSTGRESQL_PORT
              value: '5432'
            - name: POSTGRESQL_USER_SUFFIX
              value: ''
            - name: PGSSLMODE
              value: verify-ca
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: key-vault-catalog
                  key: database-name
            - name: DATABASE_OWNER
              valueFrom:
                secretKeyRef:
                  name: key-vault-catalog
                  key: database-owner-username
            - name: DATABASE_OWNER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: key-vault-catalog
                  key: database-owner-password
            - name: DATABASE_LOGIN
              valueFrom:
                secretKeyRef:
                  name: key-vault-catalog
                  key: database-login-username
            - name: DATABASE_LOGIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: key-vault-catalog
                  key: database-login-password
            - name: DATABASE_GQL_ROLE
              valueFrom:
                secretKeyRef:
                  name: key-vault-catalog
                  key: database-gql-username
            - name: RABBITMQ_PROTOCOL
              value: amqps
            - name: RABBITMQ_VHOST
              value: 16b0tks5rqq2qoobqvo5fxhfj_8j0cretxi7muq1cgjvp4fwurw
            - name: RABBITMQ_HOST
              value: rabbitmq.eu.axinom.net
            - name: RABBITMQ_PORT
              value: '5671'
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: key-vault-catalog
                  key: rabbitmq-user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: key-vault-catalog
                  key: rabbitmq-password
            - name: RABBITMQ_DEV_MIDDLEWARE
              value: 'false'
            - name: RABBITMQ_VHOST_ASSERT
              value: 'false'
            - name: RABBITMQ_MGMT_PROTOCOL
              value: https
            - name: RABBITMQ_MGMT_HOST
              value: rabbitmq.eu.axinom.net
            - name: RABBITMQ_MGMT_PORT
              value: '15671'
            - name: TENANT_ID
              value: 13d99de7-b726-45f8-a03d-7935e116b97f
            - name: ENVIRONMENT_ID
              value: 900c8d55-31d4-43ba-a73a-3f2289a7b2cc
            - name: ID_SERVICE_AUTH_BASE_URL
              value: https://id.service.eu.axinom.net
