--! Previous: sha1:ac06834674084dc237f4ac9168dfc87d7e85931c
--! Hash: sha1:aa91e2e50535a2e9c6d7964bad84dc9af4299518
--! Message: add-tables-for-channels

DROP TABLE IF EXISTS app_public.channel CASCADE;
CREATE TABLE app_public.channel(
  id TEXT PRIMARY KEY,
  title TEXT,
  description TEXT
);

DROP TABLE IF EXISTS app_public.channel_images CASCADE;
CREATE TABLE app_public.channel_images(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  channel_id TEXT REFERENCES channel ON DELETE CASCADE,
  type TEXT,
  path TEXT,
  width INTEGER,
  height INTEGER
);
CREATE INDEX ON app_public.channel_images (channel_id);

DROP TABLE IF EXISTS app_public.channel_videos CASCADE;
CREATE TABLE app_public.channel_videos(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  channel_id TEXT REFERENCES channel ON DELETE CASCADE,
  type TEXT,
  title TEXT,
  length_in_seconds NUMERIC(13,5),
  audio_languages TEXT [],
  subtitle_languages TEXT [],
  caption_languages TEXT [],
  dash_manifest TEXT,
  hls_manifest TEXT,
  is_protected BOOLEAN,
  output_format TEXT
);
SELECT ax_define.define_index('channel_id', 'channel_videos', 'app_public');
SELECT ax_define.define_index('type', 'channel_videos', 'app_public');

DROP TABLE IF EXISTS app_public.channel_video_streams CASCADE;
CREATE TABLE app_public.channel_video_streams(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  channel_video_id INTEGER REFERENCES channel_videos ON DELETE CASCADE,
  label TEXT,
  key_id TEXT,
  format TEXT,
  iv TEXT,
  file TEXT,
  language_code TEXT,
  bitrate_in_kbps INTEGER,
  file_template TEXT,
  codecs text,
  frame_rate NUMERIC(8,5),
  height INT,
  width INT,
  display_aspect_ratio TEXT,
  pixel_aspect_ratio TEXT,
  sampling_rate INT,
  language_name TEXT
);

SELECT ax_define.set_enum_as_column_type('type', 'channel_video_streams', 'app_public', 'video_stream_type', 'app_public', 'VIDEO', 'NULL');
SELECT ax_define.set_enum_domain('type', 'channel_video_streams', 'app_public', 'video_stream_type_enum', 'app_public');
SELECT ax_define.define_index('type', 'channel_video_streams', 'app_public');
SELECT ax_define.define_index('channel_video_id', 'channel_video_streams', 'app_public');

GRANT SELECT, INSERT, UPDATE, DELETE ON
  app_public.channel,
  app_public.channel_images,
  app_public.channel_videos,
  app_public.channel_video_streams TO ":DATABASE_GQL_ROLE";
