--! Previous: sha1:ac06834674084dc237f4ac9168dfc87d7e85931c
--! Hash: sha1:75abcc71fe97b30f08804271eb66200151400e8c
--! Message: add-video-cue-points-tables

DROP TABLE IF EXISTS app_public.movie_video_cue_points CASCADE;
CREATE TABLE app_public.movie_video_cue_points(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  movie_video_id INTEGER REFERENCES movie_videos ON DELETE CASCADE,
  cue_point_type_key TEXT NOT NULL,
  time_in_seconds NUMERIC(13,5) NOT NULL,
  value TEXT
);
SELECT ax_define.define_index('movie_video_id', 'movie_video_cue_points', 'app_public');


DROP TABLE IF EXISTS app_public.episode_video_cue_points CASCADE;
CREATE TABLE app_public.episode_video_cue_points(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  episode_video_id INTEGER REFERENCES episode_videos ON DELETE CASCADE,
  cue_point_type_key TEXT NOT NULL,
  time_in_seconds NUMERIC(13,5) NOT NULL,
  value TEXT
);
SELECT ax_define.define_index('episode_video_id', 'episode_video_cue_points', 'app_public');


DROP TABLE IF EXISTS app_public.season_video_cue_points CASCADE;
CREATE TABLE app_public.season_video_cue_points(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  season_video_id INTEGER REFERENCES season_videos ON DELETE CASCADE,
  cue_point_type_key TEXT NOT NULL,
  time_in_seconds NUMERIC(13,5) NOT NULL,
  value TEXT
);
SELECT ax_define.define_index('season_video_id', 'season_video_cue_points', 'app_public');


DROP TABLE IF EXISTS app_public.tvshow_video_cue_points CASCADE;
CREATE TABLE app_public.tvshow_video_cue_points(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tvshow_video_id INTEGER REFERENCES tvshow_videos ON DELETE CASCADE,
  cue_point_type_key TEXT NOT NULL,
  time_in_seconds NUMERIC(13,5) NOT NULL,
  value TEXT
);
SELECT ax_define.define_index('tvshow_video_id', 'tvshow_video_cue_points', 'app_public');

GRANT SELECT, INSERT, UPDATE, DELETE ON
  app_public.movie_video_cue_points,
  app_public.episode_video_cue_points,
  app_public.season_video_cue_points,
  app_public.tvshow_video_cue_points TO ":DATABASE_GQL_ROLE";
