--! Previous: sha1:75abcc71fe97b30f08804271eb66200151400e8c
--! Hash: sha1:66a3704e0515a63889b50a53166b99fc6e10e458
--! Message: add-tables-for-channels

DROP TABLE IF EXISTS app_public.channel CASCADE;
CREATE TABLE app_public.channel(
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  dash_stream_url TEXT,
  hls_stream_url TEXT,
  key_id TEXT
);

DROP TABLE IF EXISTS app_public.channel_images CASCADE;
CREATE TABLE app_public.channel_images(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  channel_id TEXT REFERENCES channel ON DELETE CASCADE,
  type TEXT,
  path TEXT,
  width INTEGER,
  height INTEGER
);
CREATE INDEX ON app_public.channel_images (channel_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON
  app_public.channel,
  app_public.channel_images TO ":DATABASE_GQL_ROLE";
