--! Previous: sha1:97ed7b504c3a6797066c4540a31081a76ab28c8b
--! Hash: sha1:ea969e3c1994809b866594a35deb5fa21ee69062
--! Message: reviews-added

-- review and localizations
DROP TABLE IF EXISTS app_public.review CASCADE;
CREATE TABLE app_public.review(
  id TEXT PRIMARY KEY,
  rating INT NOT NULL
);

DROP TABLE IF EXISTS app_public.review_localizations CASCADE;
CREATE TABLE IF NOT EXISTS app_public.review_localizations(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  review_id TEXT REFERENCES app_public.review ON DELETE CASCADE,
  locale TEXT NOT NULL,
  is_default_locale BOOLEAN NOT NULL,
  title TEXT NOT NULL,
  description TEXT
);

SELECT ax_define.define_index('review_id', 'review_localizations', 'app_public');
SELECT ax_define.define_index('locale', 'review_localizations', 'app_public');
SELECT ax_define.define_like_index('title', 'review_localizations', 'app_public');
SELECT ax_define.define_indexes_with_id(
  fieldName => 'title', 
  tableName => 'review_localizations', 
  schemaName => 'app_public', 
  idFieldName => 'review_id');

SELECT app_private.define_localization_view(
  'review',
  'review_localizations',
  'review_id');

GRANT SELECT ON
  app_public.review,
  app_public.review_localizations TO ":DATABASE_GQL_ROLE";
