--! Previous: sha1:8d220af7b90bc280a9165f8bcef3ccc38dd0c204
--! Hash: sha1:429f0e899d5db07d9e0acd1232eaa929b17a6832
--! Message: movie-localizations-added

-- Movies
CREATE TABLE IF NOT EXISTS app_public.movie_localizations(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  movie_id TEXT REFERENCES movie ON DELETE CASCADE,
  locale TEXT NOT NULL,
  is_default_locale BOOLEAN NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  synopsis TEXT
);

SELECT ax_define.define_index('movie_id', 'movie_localizations', 'app_public');
SELECT ax_define.define_index('locale', 'movie_localizations', 'app_public');

-- Migrate values for the default locale into the table.
DO $$ BEGIN
  IF ax_define.column_exists('title', 'movie', 'app_public') THEN
    INSERT INTO app_public.movie_localizations
    (movie_id, title, description, synopsis, locale, is_default_locale)
    SELECT m.id, m.title, m.description, m.synopsis, ':DEFAULT_LOCALE_TAG', true
    FROM app_public.movie m
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

ALTER TABLE app_public.movie DROP COLUMN IF EXISTS title;
ALTER TABLE app_public.movie DROP COLUMN IF EXISTS description;
ALTER TABLE app_public.movie DROP COLUMN IF EXISTS synopsis;

GRANT SELECT, INSERT, UPDATE, DELETE ON app_public.movie_localizations TO ":DATABASE_GQL_ROLE";

-- Movie Genres
CREATE TABLE IF NOT EXISTS app_public.movie_genre_localizations(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  movie_genre_id TEXT REFERENCES movie_genre ON DELETE CASCADE,
  locale TEXT NOT NULL,
  is_default_locale BOOLEAN NOT NULL,
  title TEXT NOT NULL
);

SELECT ax_define.define_index('movie_genre_id', 'movie_genre_localizations', 'app_public');
SELECT ax_define.define_index('locale', 'movie_genre_localizations', 'app_public');

-- Migrate values for the default locale into the table.
DO $$ BEGIN
  IF ax_define.column_exists('title', 'movie_genre', 'app_public') THEN
    INSERT INTO app_public.movie_genre_localizations
    (movie_genre_id, title, locale, is_default_locale)
    SELECT g.id, g.title, ':DEFAULT_LOCALE_TAG', true
    FROM app_public.movie_genre g
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

ALTER TABLE app_public.movie_genre DROP COLUMN IF EXISTS title;

GRANT SELECT, INSERT, UPDATE, DELETE ON app_public.movie_genre_localizations TO ":DATABASE_GQL_ROLE";
