--! Previous: sha1:7450cde0cb372030062d77be9527127598e1180f
--! Hash: sha1:a6c702858a035cb36f13575f70a7bc19528e7500
--! Message: channel-localizations-and-playlist

-- channel localizations
DROP TABLE IF EXISTS app_public.channel_localizations CASCADE;
CREATE TABLE IF NOT EXISTS app_public.channel_localizations(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  channel_id TEXT REFERENCES app_public.channel ON DELETE CASCADE,
  locale TEXT NOT NULL,
  is_default_locale BOOLEAN NOT NULL,
  title TEXT NOT NULL,
  description TEXT
);
SELECT ax_define.define_index('channel_id', 'channel_localizations', 'app_public');
SELECT ax_define.define_index('locale', 'channel_localizations', 'app_public');

ALTER TABLE app_public.channel DROP COLUMN IF EXISTS title;
ALTER TABLE app_public.channel DROP COLUMN IF EXISTS description;

SELECT app_private.define_localization_view(
  ARRAY['title', 'description'],
  'channel',
  'channel_localizations',
  'channel_id');

GRANT SELECT ON app_public.channel_localizations TO ":DATABASE_GQL_ROLE";
REVOKE INSERT, UPDATE, DELETE
  ON app_public.channel, app_public.channel_images FROM ":DATABASE_GQL_ROLE";

-- playlist and localizations
DROP TABLE IF EXISTS app_public.playlist CASCADE;
CREATE TABLE app_public.playlist(
  id TEXT PRIMARY KEY,
  channel_id TEXT REFERENCES app_public.channel ON DELETE CASCADE,
  start_date_time TIMESTAMPTZ NOT NULL,
  end_date_time TIMESTAMPTZ NOT NULL
);
SELECT ax_define.define_index('channel_id', 'playlist', 'app_public');
SELECT ax_define.define_index('start_date_time', 'playlist', 'app_public');
SELECT ax_define.define_index('end_date_time', 'playlist', 'app_public');
GRANT SELECT ON app_public.playlist TO ":DATABASE_GQL_ROLE";

-- program and localizations
DROP TABLE IF EXISTS app_public.program CASCADE;
CREATE TABLE app_public.program(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  playlist_id TEXT REFERENCES app_public.playlist(id) ON DELETE CASCADE,
  sort_index INT NOT NULL,
  movie_id TEXT,
  episode_id TEXT
);
SELECT ax_define.define_multiple_field_index(ARRAY['playlist_id','sort_index'], 'program', 'app_public');

DROP TABLE IF EXISTS app_public.program_localizations CASCADE;
CREATE TABLE IF NOT EXISTS app_public.program_localizations(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  program_id INTEGER REFERENCES app_public.program ON DELETE CASCADE,
  locale TEXT NOT NULL,
  is_default_locale BOOLEAN NOT NULL,
  title TEXT NOT NULL
);
SELECT ax_define.define_index('program_id', 'program_localizations', 'app_public');
SELECT ax_define.define_index('locale', 'program_localizations', 'app_public');

SELECT app_private.define_localization_view(
  ARRAY['title'],
  'program',
  'program_localizations',
  'program_id');

DROP TABLE IF EXISTS app_public.program_images CASCADE;
CREATE TABLE app_public.program_images(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  program_id INTEGER REFERENCES program ON DELETE CASCADE,
  type TEXT,
  path TEXT,
  width INTEGER,
  height INTEGER
);
CREATE INDEX ON app_public.program_images (program_id);

GRANT SELECT ON
  app_public.program,
  app_public.program_images,
  app_public.program_localizations TO ":DATABASE_GQL_ROLE";
