query Season($id: Int!) {
  season(id: $id) {
    index
    title
    synopsis
    description
    externalId
    rating
    contentOwner
    extendedField
    assetSubtype
    seasonsTags {
      nodes {
        name
      }
    }
    seasonsDirectors {
      nodes {
        name
      }
    }
    seasonsTvshowGenres {
      nodes {
        tvshowGenres {
          title
        }
      }
    }
    seasonsCasts {
      nodes {
        name
      }
    }
    studio
    seasonsProductionCountries {
      nodes {
        name
      }
    }
    released
    id
    createdDate
    createdUser
    updatedDate
    updatedUser
    episodes {
      totalCount
    }
    seasonsTrailers {
      totalCount
    }
    seasonsImages {
      nodes {
        imageType
        imageId
      }
    }
    publishStatus
    publishedDate
    publishedUser
    tvshow {
      id
      title
      tvshowsImages(condition: { imageType: COVER_1X1 }, first: 1) {
        nodes {
          imageId
        }
      }
    }
  }

  tvshowGenres {
    nodes {
      title
      id
    }
  }

  ageRatings {
    nodes {
      name
      id
    }
  }

  contentOwners {
    nodes {
      name
      id
    }
  }
}

mutation DeleteSeason($input: DeleteSeasonInput!) {
  deleteSeason(input: $input) {
    clientMutationId
  }
}

mutation PublishSeason($id: Int!) {
  publishSeason(seasonId: $id) {
    id
  }
}

mutation UnpublishSeason($id: Int!) {
  unpublishSeason(seasonId: $id) {
    id
  }
}

query SeasonTitle($id: Int!) {
  season(id: $id) {
    id
    index
  }
}

query SearchSeasonTags($searchKey: String!, $limit: Int!) {
  getSeasonsTagsValues(
    filter: { startsWithInsensitive: $searchKey }
    first: $limit
  ) {
    nodes
  }
}

query SearchSeasonCast($searchKey: String!, $limit: Int!) {
  getSeasonsCastsValues(
    filter: { startsWithInsensitive: $searchKey }
    first: $limit
  ) {
    nodes
  }
}

query SearchSeasonProductionCountries($searchKey: String!, $limit: Int!) {
  getSeasonsProductionCountriesValues(
    filter: { startsWithInsensitive: $searchKey }
    first: $limit
  ) {
    nodes
  }
}

query SearchSeasonDirector($searchKey: String!, $limit: Int!) {
  getSeasonsDirectorsValues(
    filter: { startsWithInsensitive: $searchKey }
    first: $limit
  ) {
    nodes
  }
}
