---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: channel
  labels:
    app: channel
    release: rancher-monitoring # Without this label, prometheus won't pick up this pod monitor.
spec:
  selector:
    matchLabels:
      app: channel
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
