---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: entitlement
  labels:
    app: entitlement
    release: rancher-monitoring # Without this label, prometheus won't pick up this pod monitor.
spec:
  selector:
    matchLabels:
      app: entitlement
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
