apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  axinom.com/platform: mosaic
  mosaic.axinom.com/service: unifiedstreaming
commonLabels:
  axinom.com/platform: mosaic
  mosaic.axinom.com/service: unifiedstreaming
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: unifiedstreaming-origin-apache-conf
    files:
      - unified-origin.apache.conf
  - name: unifiedstreaming-origin-apache-ports-conf
    files:
      - ports.conf
resources:
  - deployment.yaml
  - service.yaml
  - storageclass.yaml
  - http-route.yaml
