# This config is mounted to the container through a configmap.

AddHandler smooth-streaming.extensions .ism .isml

ServerName unified-origin

UspLicenseKey /etc/usp-license.key

<IfDefine LOG_FORMAT>
  LogFormat '${LOG_FORMAT}' log_format
</IfDefine>
<IfDefine !LOG_FORMAT>
  LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\" %D" log_format
</IfDefine>

<VirtualHost 0.0.0.0:80>
# Don't log kubernetes probes
  SetEnvIf User-Agent "kube-probe" dontlog
  CustomLog /dev/stdout log_format env=!dontlog
  ErrorLog /dev/stderr

  <IfDefine LOG_LEVEL>
    LogLevel ${LOG_LEVEL}
  </IfDefine>
  <IfDefine !LOG_LEVEL>
    LogLevel warn
  </IfDefine>

  SSLProxyEngine on

  DocumentRoot /var/www/unified-origin

  Header set Access-Control-Allow-Headers "origin, range"
  Header set Access-Control-Allow-Methods "GET, HEAD, OPTIONS"
  Header set Access-Control-Allow-Origin "*"
  Header set Access-Control-Expose-Headers "Server,range"

  # Enable Origin and use subrequests instead of libcurl
  <Location />
    UspHandleIsm on
    UspEnableSubreq on
  </Location>

</VirtualHost>


# Added outside of standard config to cache assets stored in MS Storage Account.
<VirtualHost 0.0.0.0:8081>
# Don't log kubernetes probes
  SetEnvIf User-Agent "kube-probe" dontlog
  CustomLog /dev/stdout log_format env=!dontlog
  ErrorLog /dev/stderr

  ServerName origin-cache

  CacheRoot /var/cache/apache2
  CacheEnable disk /
  CacheDirLevels 5
  CacheDirLength 3
  CacheDefaultExpire 7200
  CacheIgnoreNoLastMod On
  CacheIgnoreCacheControl On
  CacheIgnoreQueryString On
  # The max size of your index files
  CacheMaxFileSize 1000000000

  # This allows for the full dref mp4 index to be cached locally
  CacheQuickHandler off

  # Unset range to cache the index mp4s and server manifest
  # Set Cache-Control s-maxage to 7days to support caching of files when S3
  # Authentication Headers(S3UseHeaders) are enabled. If the response contains
  # an "Authorization:" header, it must also contain an "s-maxage",
  # "must-revalidate" or "public" option in the "Cache-Control:" header, or it
  # won't be cached.
  <LocationMatch ".*\.(?i:ism|xml)$">
     RequestHeader unset Range
     Header set Cache-Control "s-maxage=604800"
   </LocationMatch>

  <Location "/">
    ProxyPass ${CACHED_STORAGE_ACCOUNT_URL} connectiontimeout=5 timeout=10 ttl=300 keepalive=on retry=0
    ProxyPassReverse ${CACHED_STORAGE_ACCOUNT_URL}
  </Location>

  SetEnvIf User-Agent "kube-probe" dontlog
  CustomLog /dev/stdout log_format env=!dontlog
  ErrorLog /dev/stderr
  LogLevel debug
</VirtualHost>


<Directory /var/www/unified-origin>
  Require all granted
  Options -Indexes
</Directory>

# Optional REST API for publishing point management
<IfDefine REST_API_PORT>
  Listen 0.0.0.0:${REST_API_PORT}
  <VirtualHost 0.0.0.0:${REST_API_PORT}>
    CustomLog /dev/stdout log_format
    ErrorLog /dev/stderr

    <IfDefine LOG_LEVEL>
      LogLevel ${LOG_LEVEL}
    </IfDefine>
    <IfDefine !LOG_LEVEL>
      LogLevel warn
    </IfDefine>

    DocumentRoot /var/www/unified-origin

    # Enable REST API
    <Location />
      UspHandleApi on
    </Location>
  </VirtualHost>
</IfDefine>
