apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: '10503'
    prometheus.io/scrape: 'true'
  name: catalog
spec:
  type: ClusterIP
  selector:
    app: catalog
  ports:
    - name: app
      port: 10300
      protocol: TCP
      targetPort: 10300
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: diagnostics
      port: 9911
      protocol: TCP
      targetPort: 9911
