apiVersion: apps/v1
kind: Deployment
metadata:
  name: vod-to-live
spec:
  template:
    spec:
      containers:
        - name: app
          env:
            - name: NODE_ENV
              value: test
            - name: LOG_LEVEL
              value: DEBUG
            - name: RABBITMQ_PROTOCOL
              value: amqps
            - name: RABBITMQ_VHOST
              value: wv6ypvgnbca9op5fkz5xah5p_ecc5zfwhykx6c5ohthlz28mxm
            - name: RABBITMQ_HOST
              value: rabbitmq.cb.axinom.net
            - name: RABBITMQ_PORT
              value: '5671'
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: key-vault-entitlement
                  key: rabbitmq-user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: key-vault-entitlement
                  key: rabbitmq-password
            - name: RABBITMQ_DEV_MIDDLEWARE
              value: 'false'
            - name: RABBITMQ_VHOST_ASSERT
              value: 'false'
            - name: RABBITMQ_MGMT_PROTOCOL
              value: https
            - name: RABBITMQ_MGMT_HOST
              value: rabbitmq-mgt.cb.axinom.net
            - name: RABBITMQ_MGMT_PORT
              value: '443'
            - name: TENANT_ID
              value: 0f6bc3c4-9e70-4aba-9dfe-8bf32be99a5d
            - name: ENVIRONMENT_ID
              value: f2440a8a-eb88-41ba-832b-752c364d641a
            - name: VIRTUAL_CHANNEL_MANAGEMENT_API_BASE_URL
              value: 'https://cb-navy-streaming-api.axtest.net'
            - name: VIRTUAL_CHANNEL_ORIGIN_BASE_URL
              value: 'https://cb-navy-streaming-origin.axtest.net'
            - name: AZURE_STORAGE_CONNECTION
              value: '-'
            - name: AZURE_BLOB_CONTAINER_NAME
              value: 'vod2live'
            - name: VIRTUAL_CHANNEL_MANAGEMENT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: key-vault-vod-to-live
                  key: api-key
            - name: PRE_PUBLISHING_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: key-vault-vod-to-live
                  key: pre-publishing-webhook-secret
            - name: SERVICE_ACCOUNT_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: key-vault-vod-to-live
                  key: service-account-client-id
            - name: SERVICE_ACCOUNT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: key-vault-vod-to-live
                  key: service-account-client-secret
            - name: ID_SERVICE_AUTH_BASE_URL
              value: https://id.service.test.axinom.net
