import {
  Mutations as M,
  Queries as Q,
  Relations as R,
  Subscriptions as S,
} from '../../generated/graphql/operations';

export enum Sub { // Required to allow requesting these endpoints as child properties. Endpoints are excluded from the root Query via smart tags.
  tvshowsSnapshots = 'tvshowsSnapshots',
  seasonsSnapshots = 'seasonsSnapshots',
  episodesSnapshots = 'episodesSnapshots',
  snapshotValidationResults = 'snapshotValidationResults',
}

export const TvShowAdditionalOperations = [
  Sub.tvshowsSnapshots,
  Sub.seasonsSnapshots,
  Sub.episodesSnapshots,
  Sub.snapshotValidationResults,
];

export const TvShowIgnoreOperations = [
  Q.episodesImage,
  Q.seasonsImage,
  Q.tvshowsImage,
  Q.tvshowGenreBySortOrder,
  M.updateTvshowGenreBySortOrder,
  M.deleteTvshowGenreBySortOrder,
];

export const TvShowGenresReadOperations = [
  Q.tvshowGenre,
  Q.tvshowGenres,
  S.tvshowGenreMutated,
  R.tvshowsTvshowGenresByTvshowGenresId,
  R.seasonsTvshowGenresByTvshowGenresId,
  R.episodesTvshowGenresByTvshowGenresId,
];

export const TvShowGenresMutateOperations = [
  M.createTvshowGenre,
  M.deleteTvshowGenre,
  M.deleteTvshowGenres,
  M.updateTvshowGenre,
  M.publishTvshowGenres,
  M.unpublishTvshowGenres,
  M.createTvshowGenresSnapshot,
];

export const TvShowsReadOperations = [
  Q.getTvshowsCastsValues,
  Q.getTvshowsProductionCountriesValues,
  Q.getTvshowsTagsValues,
  Q.tvshow,
  Q.tvshowByExternalId,
  Q.tvshows,
  Q.tvshowsCast,
  Q.tvshowsCasts,
  Q.tvshowsImages,
  Q.tvshowsLicense,
  Q.tvshowsLicenses,
  Q.tvshowsLicensesCountries,
  Q.tvshowsLicensesCountry,
  Q.tvshowsProductionCountries,
  Q.tvshowsProductionCountry,
  Q.tvshowsTag,
  Q.tvshowsTags,
  Q.tvshowsTrailer,
  Q.tvshowsTrailers,
  Q.tvshowsTvshowGenre,
  Q.tvshowsTvshowGenres,
  S.tvshowMutated,
  Sub.tvshowsSnapshots,
  Sub.snapshotValidationResults,
  R.tvshowGenres,
];

export const TvShowsMutateOperations = [
  M.createTvshow,
  M.createTvshowsCast,
  M.createTvshowsImage,
  M.createTvshowsLicense,
  M.createTvshowsLicensesCountry,
  M.createTvshowsProductionCountry,
  M.createTvshowsTag,
  M.createTvshowsTrailer,
  M.createTvshowsTvshowGenre,
  M.deleteTvshow,
  M.deleteTvshowByExternalId,
  M.deleteTvshows,
  M.deleteTvshowsCast,
  M.deleteTvshowsImageByTvshowIdAndImageType,
  M.deleteTvshowsLicense,
  M.deleteTvshowsLicenses,
  M.deleteTvshowsLicensesCountry,
  M.deleteTvshowsProductionCountry,
  M.deleteTvshowsTag,
  M.deleteTvshowsTrailer,
  M.deleteTvshowsTvshowGenre,
  M.publishTvshows,
  M.updateTvshow,
  M.updateTvshowByExternalId,
  M.updateTvshowsCast,
  M.updateTvshowsImageByTvshowIdAndImageType,
  M.updateTvshowsLicense,
  M.updateTvshowsLicensesCountry,
  M.updateTvshowsProductionCountry,
  M.updateTvshowsTag,
  M.publishTvshow,
  M.publishTvshows,
  M.unpublishTvshow,
  M.unpublishTvshows,
  M.createTvshowSnapshot,
  M.createTvshowSnapshots,
];

export const SeasonsReadOperations = [
  Q.getSeasonsCastsValues,
  Q.getSeasonsProductionCountriesValues,
  Q.getSeasonsTagsValues,
  Q.season,
  Q.seasonByExternalId,
  Q.seasons,
  Q.seasonsCast,
  Q.seasonsCasts,
  Q.seasonsImages,
  Q.seasonsLicense,
  Q.seasonsLicenses,
  Q.seasonsLicensesCountries,
  Q.seasonsLicensesCountry,
  Q.seasonsProductionCountries,
  Q.seasonsProductionCountry,
  Q.seasonsTag,
  Q.seasonsTags,
  Q.seasonsTrailer,
  Q.seasonsTrailers,
  Q.seasonsTvshowGenre,
  Q.seasonsTvshowGenres,
  S.seasonMutated,
  Sub.seasonsSnapshots,
  Sub.snapshotValidationResults,
];

export const SeasonsMutateOperations = [
  M.createSeason,
  M.createSeasonsCast,
  M.createSeasonsImage,
  M.createSeasonsLicense,
  M.createSeasonsLicensesCountry,
  M.createSeasonsProductionCountry,
  M.createSeasonsTag,
  M.createSeasonsTrailer,
  M.createSeasonsTvshowGenre,
  M.deleteSeason,
  M.deleteSeasonByExternalId,
  M.deleteSeasons,
  M.deleteSeasonsCast,
  M.deleteSeasonsImageBySeasonIdAndImageType,
  M.deleteSeasonsLicense,
  M.deleteSeasonsLicenses,
  M.deleteSeasonsLicensesCountry,
  M.deleteSeasonsProductionCountry,
  M.deleteSeasonsTag,
  M.deleteSeasonsTrailer,
  M.deleteSeasonsTvshowGenre,
  M.publishSeasons,
  M.updateSeason,
  M.updateSeasonByExternalId,
  M.updateSeasonsCast,
  M.updateSeasonsImageBySeasonIdAndImageType,
  M.updateSeasonsLicense,
  M.updateSeasonsLicensesCountry,
  M.updateSeasonsProductionCountry,
  M.updateSeasonsTag,
  M.publishSeason,
  M.publishSeasons,
  M.unpublishSeason,
  M.unpublishSeasons,
  M.createSeasonSnapshot,
  M.createSeasonSnapshots,
];

export const EpisodesReadOperations = [
  Q.episode,
  Q.episodeByExternalId,
  Q.episodes,
  Q.episodesCast,
  Q.episodesCasts,
  Q.episodesImages,
  Q.episodesLicense,
  Q.episodesLicenses,
  Q.episodesLicensesCountries,
  Q.episodesLicensesCountry,
  Q.episodesProductionCountries,
  Q.episodesProductionCountry,
  Q.episodesTag,
  Q.episodesTags,
  Q.episodesTrailer,
  Q.episodesTrailers,
  Q.episodesTvshowGenre,
  Q.episodesTvshowGenres,
  Q.getEpisodesCastsValues,
  Q.getEpisodesProductionCountriesValues,
  Q.getEpisodesTagsValues,
  S.episodeMutated,
  Sub.episodesSnapshots,
  Sub.snapshotValidationResults,
];

export const EpisodesMutateOperations = [
  M.createEpisode,
  M.createEpisodesCast,
  M.createEpisodesImage,
  M.createEpisodesLicense,
  M.createEpisodesLicensesCountry,
  M.createEpisodesProductionCountry,
  M.createEpisodesTag,
  M.createEpisodesTrailer,
  M.createEpisodesTvshowGenre,
  M.deleteEpisode,
  M.deleteEpisodeByExternalId,
  M.deleteEpisodes,
  M.deleteEpisodesCast,
  M.deleteEpisodesImageByEpisodeIdAndImageType,
  M.deleteEpisodesLicense,
  M.deleteEpisodesLicenses,
  M.deleteEpisodesLicensesCountry,
  M.deleteEpisodesProductionCountry,
  M.deleteEpisodesTag,
  M.deleteEpisodesTrailer,
  M.deleteEpisodesTvshowGenre,
  M.publishEpisodes,
  M.updateEpisode,
  M.updateEpisodeByExternalId,
  M.updateEpisodesCast,
  M.updateEpisodesImageByEpisodeIdAndImageType,
  M.updateEpisodesLicense,
  M.updateEpisodesLicensesCountry,
  M.updateEpisodesProductionCountry,
  M.updateEpisodesTag,
  M.publishEpisode,
  M.publishEpisodes,
  M.unpublishEpisode,
  M.unpublishEpisodes,
  M.createEpisodeSnapshot,
  M.createEpisodeSnapshots,
];

export const TvshowsDevOperations = [M.populateTvshows];
