---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azureblob-fuse-premium
provisioner: blob.csi.azure.com
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - -o allow_other

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-retain
provisioner: disk.csi.azure.com
parameters:
  cachingmode: ReadOnly
  kind: Managed
  storageaccounttype: StandardSSD_LRS
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
