query SeasonsLicenses(
  $filter: SeasonsLicenseFilter
  $orderBy: [SeasonsLicensesOrderBy!]
  $after: Cursor
) {
  seasonsLicenses(
    filter: $filter
    orderBy: $orderBy
    first: 30
    after: $after
  ) {
    totalCount
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      id
      seasonsLicensesCountries {
        nodes {
          countryCode
          countryGroupId
        }
      }
      licenseEnd
      licenseStart
    }
  }
}

query GetAllCountryData {
  allCountryTypes(orderBy: NAME_ASC) {
    nodes {
      name
      id
    }
  }
}
