query MoviesLicense($id: Int!) {
  moviesLicense(id: $id) {
    moviesLicensesCountries {
      nodes {
        countryCode
        countryGroupId
        id
      }
    }
    licenseEnd
    licenseStart
    movieId
    createdDate
    updatedDate
    updatedUser
    createdUser
    isDownloadable
    downloadedAssetLifespan
  }
  allCountryTypes(orderBy: NAME_ASC) {
    nodes {
      name
      id
    }
  }
}

mutation UpdateMoviesLicense($input: UpdateMoviesLicenseInput!) {
  updateMoviesLicense(input: $input) {
    clientMutationId
  }
}

mutation DeleteMoviesLicense($input: DeleteMoviesLicenseInput!) {
  deleteMoviesLicense(input: $input) {
    clientMutationId
  }
}
