fragment TVShowExplorerProperties on Tvshow {
  id
  publishStatus
  title
  externalId
  ageRating
  assetSubtype
  businessType
  contentOwner
  tvshowsImages(
    filter: {
      imageType: { in: [TVSHOW_COVER_1X1, TVSHOW_COVER_16X9, TVSHOW_COVER] }
    }
    orderBy: IMAGE_TYPE_DESC
  ) {
    nodes {
      imageId
    }
  }
  tvshowsTvshowGenres {
    nodes {
      tvshowGenres {
        title
      }
    }
  }
  createdDate
  updatedDate
  updatedUser
  originalTitle
  tvshowsTags {
    nodes {
      name
    }
  }
  tvshowsCasts {
    nodes {
      name
    }
  }
  released
  tvshowsProductionCountries {
    nodes {
      name
    }
  }
  tvshowsLicenses {
    nodes {
      licenseEnd
      licenseStart
      tvshowsLicensesCountries {
        nodes {
          countryCode
          countryGroupId
        }
      }
    }
  }
  publishedDate
  publishingId
  seasons {
    nodes {
      episodes {
        nodes {
          episodesLicenses {
            nodes {
              licenseStart
              licenseEnd
            }
          }
        }
      }
    }
  }
}

query TVShows(
  $filter: TvshowFilter
  $orderBy: [TvshowsOrderBy!]
  $after: Cursor
) {
  filtered: tvshows(
    filter: $filter
    orderBy: $orderBy
    first: 30
    after: $after
  ) {
    totalCount
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      ...TVShowExplorerProperties
    }
  }
  nonFiltered: tvshows {
    totalCount
  }
}

subscription TVShowsMutated {
  tvshowMutated {
    id
    eventKey
    tvshow {
      ...TVShowExplorerProperties
    }
  }
}

query GetTvShowsFilterOptionsData {
  ageRatings {
    nodes {
      id
      name
    }
  }

  contentOwners {
    nodes {
      id
      name
    }
  }

  movieGenres {
    nodes {
      id
      title
    }
  }

  allCountryTypes(orderBy: NAME_ASC) {
    nodes {
      name
      id
    }
  }
}
