apiVersion: apps/v1
kind: Deployment
metadata:
  name: vod-to-live
spec:
  template:
    spec:
      nodeSelector:
        mosaic.axinom.com/workload_type: customizable-services
        mosaic.axinom.com/hosting_node_pool: basic_balanced_axinom_owned
      tolerations:
        - key: 'mosaic.axinom.com/customizable-services'
          operator: 'Equal'
          value: 'True'
          effect: 'NoSchedule'
      containers:
        - name: app
          env:
            - name: NODE_ENV
              value: production
            - name: LOG_LEVEL
              value: DEBUG
            - name: RABBITMQ_PROTOCOL
              value: amqps
            - name: RABBITMQ_VHOST
              value: 16b0tks5rqq2qoobqvo5fxhfj_8j0cretxi7muq1cgjvp4fwurw
            - name: RABBITMQ_HOST
              value: rabbitmq.eu.axinom.net
            - name: RABBITMQ_PORT
              value: '5671'
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: key-vault-entitlement
                  key: rabbitmq-user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: key-vault-entitlement
                  key: rabbitmq-password
            - name: RABBITMQ_DEV_MIDDLEWARE
              value: 'false'
            - name: RABBITMQ_VHOST_ASSERT
              value: 'false'
            - name: RABBITMQ_MGMT_PROTOCOL
              value: https
            - name: RABBITMQ_MGMT_HOST
              value: rabbitmq-mgt.eu.axinom.net
            - name: RABBITMQ_MGMT_PORT
              value: '443'
            - name: TENANT_ID
              value: 13d99de7-b726-45f8-a03d-7935e116b97f
            - name: ENVIRONMENT_ID
              value: 900c8d55-31d4-43ba-a73a-3f2289a7b2cc
            - name: VIRTUAL_CHANNEL_MANAGEMENT_API_BASE_URL
              value: 'https://mosaic-streaming-api.axprod.net'
            - name: VIRTUAL_CHANNEL_ORIGIN_BASE_URL
              value: 'https://mosaic-streaming-origin.axprod.net'
            - name: AZURE_STORAGE_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: key-vault-vod-to-live
                  key: azure-storage-connection
            - name: AZURE_BLOB_CONTAINER_NAME
              value: 'vod2live'
            - name: VIRTUAL_CHANNEL_MANAGEMENT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: key-vault-vod-to-live
                  key: api-key
            - name: SERVICE_ACCOUNT_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: key-vault-vod-to-live
                  key: service-account-client-id
            - name: SERVICE_ACCOUNT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: key-vault-vod-to-live
                  key: service-account-client-secret
            - name: ID_SERVICE_AUTH_BASE_URL
              value: https://id.service.eu.axinom.net
