fragment SeasonExplorerProperties on Season {
  id
  publishStatus
  index
  externalId
  ageRating
  contentOwner
  title
  tvshow {
    id
    title
  }
  seasonsImages(
    filter: {
      imageType: { in: [SEASON_COVER_1X1, SEASON_COVER_16X9, SEASON_COVER] }
    }
    orderBy: IMAGE_TYPE_DESC
  ) {
    nodes {
      imageId
    }
  }
  seasonsTvshowGenres {
    nodes {
      tvshowGenres {
        title
      }
    }
  }
  createdDate
  updatedDate
  updatedUser
  seasonsTags {
    nodes {
      name
    }
  }
  seasonsCasts {
    nodes {
      name
    }
  }
  released
  seasonsProductionCountries {
    nodes {
      name
    }
  }
  seasonsLicenses {
    nodes {
      licenseEnd
      licenseStart
      seasonsLicensesCountries {
        nodes {
          countryCode
          countryGroupId
        }
      }
    }
  }
  publishedDate
}

query Seasons(
  $filter: SeasonFilter
  $orderBy: [SeasonsOrderBy!]
  $after: Cursor
) {
  filtered: seasons(
    filter: $filter
    orderBy: $orderBy
    first: 30
    after: $after
  ) {
    totalCount
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      ...SeasonExplorerProperties
    }
  }
  nonFiltered: seasons {
    totalCount
  }
}

subscription SeasonsMutated {
  seasonMutated {
    id
    eventKey
    season {
      ...SeasonExplorerProperties
    }
  }
}

query GetSeasonsFilterOptionsData {
  ageRatings {
    nodes {
      id
      name
    }
  }

  contentOwners {
    nodes {
      id
      name
    }
  }

  movieGenres {
    nodes {
      id
      title
    }
  }

  allCountryTypes(orderBy: NAME_ASC) {
    nodes {
      name
      id
    }
  }
}
