---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: channel-app
spec:
  hostnames:
    - cb-navy-channel.axtest.net
  parentRefs:
    - name: mosaic
      namespace: gateway
  rules:
    - backendRefs:
        - name: channel
          port: 11800
      matches:
        - path:
            type: PathPrefix
            value: /
