query TvshowsLicense($id: Int!) {
  tvshowsLicense(id: $id) {
    tvshowsLicensesCountries {
      nodes {
        code
      }
    }
    licenseEnd
    licenseStart
    tvshowId
    createdDate
    updatedDate
    updatedUser
    createdUser
    isDownloadable
    downloadedAssetLifespan
  }
}

mutation UpdateTvshowsLicense($input: UpdateTvshowsLicenseInput!) {
  updateTvshowsLicense(input: $input) {
    clientMutationId
  }
}

mutation DeleteTvshowsLicense($input: DeleteTvshowsLicenseInput!) {
  deleteTvshowsLicense(input: $input) {
    clientMutationId
  }
}
