query TvshowsLicense($id: Int!) {
  tvshowsLicense(id: $id) {
    tvshowsLicensesCountries {
      nodes {
        countryCode
        countryGroupId
        id
      }
    }
    licenseEnd
    licenseStart
    tvshowId
    createdDate
    updatedDate
    updatedUser
    createdUser
    isDownloadable
    downloadedAssetLifespan
  }
  allCountryTypes(orderBy: NAME_ASC) {
    nodes {
      name
      id
    }
  }
}

mutation UpdateTvshowsLicense($input: UpdateTvshowsLicenseInput!) {
  updateTvshowsLicense(input: $input) {
    clientMutationId
  }
}

mutation DeleteTvshowsLicense($input: DeleteTvshowsLicenseInput!) {
  deleteTvshowsLicense(input: $input) {
    clientMutationId
  }
}
