export const SECOND_IN_MILLISECONDS = 1000;
export const HOUR_IN_SECONDS = 60 * 60;
export const DAY_IN_SECONDS = 24 * HOUR_IN_SECONDS;
export const MINUTE_IN_MILLISECONDS = 60 * SECOND_IN_MILLISECONDS;
