fragment MovieExplorerProperties on Movie {
  id
  title
  originalTitle
  externalId
  mainVideoId
  ageRating
  contentOwner
  businessType
  audioLanguages
  assetSubtype
  moviesImages(condition: { imageType: COVER }) {
    nodes {
      imageId
    }
  }
  moviesTags {
    nodes {
      name
    }
  }
  moviesMovieGenres {
    nodes {
      movieGenres {
        title
      }
    }
  }
  moviesCasts {
    nodes {
      name
    }
  }
  released
  moviesProductionCountries {
    nodes {
      name
    }
  }
  collectionRelations {
    nodes {
      collection {
        title
      }
    }
  }
  studio
  publishedDate
  createdDate
  updatedDate
  updatedUser
  publishStatus
  __typename
}

query Movies($filter: MovieFilter, $orderBy: [MoviesOrderBy!], $after: Cursor) {
  filtered: movies(
    filter: $filter
    orderBy: $orderBy
    first: 30
    after: $after
  ) {
    totalCount
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      ...MovieExplorerProperties
    }
  }
  nonFiltered: movies {
    totalCount
  }
}

subscription MoviesMutated {
  movieMutated {
    id
    eventKey
    movie {
      ...MovieExplorerProperties
    }
  }
}
