--! Previous: sha1:e66ba6e5592b8ffb61ca76d5e71caff9e9eac3b4
--! Hash: sha1:586165918b2f3a24e754f0641fc750c40492c508
--! Message: switch-from-3-to-2-letter-country-codes

CREATE OR REPLACE FUNCTION app_private.three_to_two_letter_country_code(val text) RETURNS TEXT LANGUAGE SQL AS $$
  SELECT CASE val
          WHEN 'AFG' THEN 'AF'
          WHEN 'ALB' THEN 'AL'
          WHEN 'DZA' THEN 'DZ'
          WHEN 'ASM' THEN 'AS'
          WHEN 'AND' THEN 'AD'
          WHEN 'AGO' THEN 'AO'
          WHEN 'AIA' THEN 'AI'
          WHEN 'ATA' THEN 'AQ'
          WHEN 'ATG' THEN 'AG'
          WHEN 'ARG' THEN 'AR'
          WHEN 'ARM' THEN 'AM'
          WHEN 'ABW' THEN 'AW'
          WHEN 'AUS' THEN 'AU'
          WHEN 'AUT' THEN 'AT'
          WHEN 'AZE' THEN 'AZ'
          WHEN 'BHS' THEN 'BS'
          WHEN 'BHR' THEN 'BH'
          WHEN 'BGD' THEN 'BD'
          WHEN 'BRB' THEN 'BB'
          WHEN 'BLR' THEN 'BY'
          WHEN 'BEL' THEN 'BE'
          WHEN 'BLZ' THEN 'BZ'
          WHEN 'BEN' THEN 'BJ'
          WHEN 'BMU' THEN 'BM'
          WHEN 'BTN' THEN 'BT'
          WHEN 'BOL' THEN 'BO'
          WHEN 'BES' THEN 'BQ'
          WHEN 'BIH' THEN 'BA'
          WHEN 'BWA' THEN 'BW'
          WHEN 'BVT' THEN 'BV'
          WHEN 'BRA' THEN 'BR'
          WHEN 'IOT' THEN 'IO'
          WHEN 'BRN' THEN 'BN'
          WHEN 'BGR' THEN 'BG'
          WHEN 'BFA' THEN 'BF'
          WHEN 'BDI' THEN 'BI'
          WHEN 'CPV' THEN 'CV'
          WHEN 'KHM' THEN 'KH'
          WHEN 'CMR' THEN 'CM'
          WHEN 'CAN' THEN 'CA'
          WHEN 'CYM' THEN 'KY'
          WHEN 'CAF' THEN 'CF'
          WHEN 'TCD' THEN 'TD'
          WHEN 'CHL' THEN 'CL'
          WHEN 'CHN' THEN 'CN'
          WHEN 'CXR' THEN 'CX'
          WHEN 'CCK' THEN 'CC'
          WHEN 'COL' THEN 'CO'
          WHEN 'COM' THEN 'KM'
          WHEN 'COD' THEN 'CD'
          WHEN 'COG' THEN 'CG'
          WHEN 'COK' THEN 'CK'
          WHEN 'CRI' THEN 'CR'
          WHEN 'HRV' THEN 'HR'
          WHEN 'CUB' THEN 'CU'
          WHEN 'CUW' THEN 'CW'
          WHEN 'CYP' THEN 'CY'
          WHEN 'CZE' THEN 'CZ'
          WHEN 'CIV' THEN 'CI'
          WHEN 'DNK' THEN 'DK'
          WHEN 'DJI' THEN 'DJ'
          WHEN 'DMA' THEN 'DM'
          WHEN 'DOM' THEN 'DO'
          WHEN 'ECU' THEN 'EC'
          WHEN 'EGY' THEN 'EG'
          WHEN 'SLV' THEN 'SV'
          WHEN 'GNQ' THEN 'GQ'
          WHEN 'ERI' THEN 'ER'
          WHEN 'EST' THEN 'EE'
          WHEN 'SWZ' THEN 'SZ'
          WHEN 'ETH' THEN 'ET'
          WHEN 'FLK' THEN 'FK'
          WHEN 'FRO' THEN 'FO'
          WHEN 'FJI' THEN 'FJ'
          WHEN 'FIN' THEN 'FI'
          WHEN 'FRA' THEN 'FR'
          WHEN 'GUF' THEN 'GF'
          WHEN 'PYF' THEN 'PF'
          WHEN 'ATF' THEN 'TF'
          WHEN 'GAB' THEN 'GA'
          WHEN 'GMB' THEN 'GM'
          WHEN 'GEO' THEN 'GE'
          WHEN 'DEU' THEN 'DE'
          WHEN 'GHA' THEN 'GH'
          WHEN 'GIB' THEN 'GI'
          WHEN 'GRC' THEN 'GR'
          WHEN 'GRL' THEN 'GL'
          WHEN 'GRD' THEN 'GD'
          WHEN 'GLP' THEN 'GP'
          WHEN 'GUM' THEN 'GU'
          WHEN 'GTM' THEN 'GT'
          WHEN 'GGY' THEN 'GG'
          WHEN 'GIN' THEN 'GN'
          WHEN 'GNB' THEN 'GW'
          WHEN 'GUY' THEN 'GY'
          WHEN 'HTI' THEN 'HT'
          WHEN 'HMD' THEN 'HM'
          WHEN 'VAT' THEN 'VA'
          WHEN 'HND' THEN 'HN'
          WHEN 'HKG' THEN 'HK'
          WHEN 'HUN' THEN 'HU'
          WHEN 'ISL' THEN 'IS'
          WHEN 'IND' THEN 'IN'
          WHEN 'IDN' THEN 'ID'
          WHEN 'IRN' THEN 'IR'
          WHEN 'IRQ' THEN 'IQ'
          WHEN 'IRL' THEN 'IE'
          WHEN 'IMN' THEN 'IM'
          WHEN 'ISR' THEN 'IL'
          WHEN 'ITA' THEN 'IT'
          WHEN 'JAM' THEN 'JM'
          WHEN 'JPN' THEN 'JP'
          WHEN 'JEY' THEN 'JE'
          WHEN 'JOR' THEN 'JO'
          WHEN 'KAZ' THEN 'KZ'
          WHEN 'KEN' THEN 'KE'
          WHEN 'KIR' THEN 'KI'
          WHEN 'PRK' THEN 'KP'
          WHEN 'KOR' THEN 'KR'
          WHEN 'KWT' THEN 'KW'
          WHEN 'KGZ' THEN 'KG'
          WHEN 'LAO' THEN 'LA'
          WHEN 'LVA' THEN 'LV'
          WHEN 'LBN' THEN 'LB'
          WHEN 'LSO' THEN 'LS'
          WHEN 'LBR' THEN 'LR'
          WHEN 'LBY' THEN 'LY'
          WHEN 'LIE' THEN 'LI'
          WHEN 'LTU' THEN 'LT'
          WHEN 'LUX' THEN 'LU'
          WHEN 'MAC' THEN 'MO'
          WHEN 'MDG' THEN 'MG'
          WHEN 'MWI' THEN 'MW'
          WHEN 'MYS' THEN 'MY'
          WHEN 'MDV' THEN 'MV'
          WHEN 'MLI' THEN 'ML'
          WHEN 'MLT' THEN 'MT'
          WHEN 'MHL' THEN 'MH'
          WHEN 'MTQ' THEN 'MQ'
          WHEN 'MRT' THEN 'MR'
          WHEN 'MUS' THEN 'MU'
          WHEN 'MYT' THEN 'YT'
          WHEN 'MEX' THEN 'MX'
          WHEN 'FSM' THEN 'FM'
          WHEN 'MDA' THEN 'MD'
          WHEN 'MCO' THEN 'MC'
          WHEN 'MNG' THEN 'MN'
          WHEN 'MNE' THEN 'ME'
          WHEN 'MSR' THEN 'MS'
          WHEN 'MAR' THEN 'MA'
          WHEN 'MOZ' THEN 'MZ'
          WHEN 'MMR' THEN 'MM'
          WHEN 'NAM' THEN 'NA'
          WHEN 'NRU' THEN 'NR'
          WHEN 'NPL' THEN 'NP'
          WHEN 'NLD' THEN 'NL'
          WHEN 'NCL' THEN 'NC'
          WHEN 'NZL' THEN 'NZ'
          WHEN 'NIC' THEN 'NI'
          WHEN 'NER' THEN 'NE'
          WHEN 'NGA' THEN 'NG'
          WHEN 'NIU' THEN 'NU'
          WHEN 'NFK' THEN 'NF'
          WHEN 'MNP' THEN 'MP'
          WHEN 'NOR' THEN 'NO'
          WHEN 'OMN' THEN 'OM'
          WHEN 'PAK' THEN 'PK'
          WHEN 'PLW' THEN 'PW'
          WHEN 'PSE' THEN 'PS'
          WHEN 'PAN' THEN 'PA'
          WHEN 'PNG' THEN 'PG'
          WHEN 'PRY' THEN 'PY'
          WHEN 'PER' THEN 'PE'
          WHEN 'PHL' THEN 'PH'
          WHEN 'PCN' THEN 'PN'
          WHEN 'POL' THEN 'PL'
          WHEN 'PRT' THEN 'PT'
          WHEN 'PRI' THEN 'PR'
          WHEN 'QAT' THEN 'QA'
          WHEN 'MKD' THEN 'MK'
          WHEN 'ROU' THEN 'RO'
          WHEN 'RUS' THEN 'RU'
          WHEN 'RWA' THEN 'RW'
          WHEN 'REU' THEN 'RE'
          WHEN 'BLM' THEN 'BL'
          WHEN 'SHN' THEN 'SH'
          WHEN 'KNA' THEN 'KN'
          WHEN 'LCA' THEN 'LC'
          WHEN 'MAF' THEN 'MF'
          WHEN 'SPM' THEN 'PM'
          WHEN 'VCT' THEN 'VC'
          WHEN 'WSM' THEN 'WS'
          WHEN 'SMR' THEN 'SM'
          WHEN 'STP' THEN 'ST'
          WHEN 'SAU' THEN 'SA'
          WHEN 'SEN' THEN 'SN'
          WHEN 'SRB' THEN 'RS'
          WHEN 'SYC' THEN 'SC'
          WHEN 'SLE' THEN 'SL'
          WHEN 'SGP' THEN 'SG'
          WHEN 'SXM' THEN 'SX'
          WHEN 'SVK' THEN 'SK'
          WHEN 'SVN' THEN 'SI'
          WHEN 'SLB' THEN 'SB'
          WHEN 'SOM' THEN 'SO'
          WHEN 'ZAF' THEN 'ZA'
          WHEN 'SGS' THEN 'GS'
          WHEN 'SSD' THEN 'SS'
          WHEN 'ESP' THEN 'ES'
          WHEN 'LKA' THEN 'LK'
          WHEN 'SDN' THEN 'SD'
          WHEN 'SUR' THEN 'SR'
          WHEN 'SJM' THEN 'SJ'
          WHEN 'SWE' THEN 'SE'
          WHEN 'CHE' THEN 'CH'
          WHEN 'SYR' THEN 'SY'
          WHEN 'TWN' THEN 'TW'
          WHEN 'TJK' THEN 'TJ'
          WHEN 'TZA' THEN 'TZ'
          WHEN 'THA' THEN 'TH'
          WHEN 'TLS' THEN 'TL'
          WHEN 'TGO' THEN 'TG'
          WHEN 'TKL' THEN 'TK'
          WHEN 'TON' THEN 'TO'
          WHEN 'TTO' THEN 'TT'
          WHEN 'TUN' THEN 'TN'
          WHEN 'TUR' THEN 'TR'
          WHEN 'TKM' THEN 'TM'
          WHEN 'TCA' THEN 'TC'
          WHEN 'TUV' THEN 'TV'
          WHEN 'UGA' THEN 'UG'
          WHEN 'UKR' THEN 'UA'
          WHEN 'ARE' THEN 'AE'
          WHEN 'GBR' THEN 'GB'
          WHEN 'UMI' THEN 'UM'
          WHEN 'USA' THEN 'US'
          WHEN 'URY' THEN 'UY'
          WHEN 'UZB' THEN 'UZ'
          WHEN 'VUT' THEN 'VU'
          WHEN 'VEN' THEN 'VE'
          WHEN 'VNM' THEN 'VN'
          WHEN 'VGB' THEN 'VG'
          WHEN 'VIR' THEN 'VI'
          WHEN 'WLF' THEN 'WF'
          WHEN 'ESH' THEN 'EH'
          WHEN 'YEM' THEN 'YE'
          WHEN 'ZMB' THEN 'ZM'
          WHEN 'ZWE' THEN 'ZW'
          WHEN 'ALA' THEN 'AX'
          ELSE val
       END;
$$;	

SELECT ax_define.unbind_enum_type_from_table('code', 'episodes_licenses_countries', 'app_public');
SELECT ax_define.unbind_enum_type_from_table('code', 'seasons_licenses_countries', 'app_public');
SELECT ax_define.unbind_enum_type_from_table('code', 'tvshows_licenses_countries', 'app_public');
SELECT ax_define.unbind_enum_type_from_table('code', 'movies_licenses_countries', 'app_public');
		
update app_public.episodes_licenses_countries
  set code = app_private.three_to_two_letter_country_code(code);
		
update app_public.seasons_licenses_countries
  set code = app_private.three_to_two_letter_country_code(code);
		
update app_public.tvshows_licenses_countries
  set code = app_private.three_to_two_letter_country_code(code);
		
update app_public.movies_licenses_countries
  set code = app_private.three_to_two_letter_country_code(code);

DO $$ BEGIN   
  IF EXISTS(SELECT FROM information_schema.tables WHERE table_schema = 'app_public' AND table_name = 'iso_alpha_three_country_codes')
  THEN
    update app_public.iso_alpha_three_country_codes
      set value = app_private.three_to_two_letter_country_code(value);
  END IF;
END $$;

ALTER TABLE IF EXISTS app_public.iso_alpha_three_country_codes RENAME TO iso_alpha_two_country_codes;
ALTER INDEX IF EXISTS iso_alpha_three_country_codes_pkey RENAME TO iso_alpha_two_country_codes_pkey;

DO $$ BEGIN   
  IF EXISTS(SELECT typname FROM pg_catalog.pg_type where typname='iso_alpha_three_country_codes_enum')
  THEN
    ALTER DOMAIN iso_alpha_three_country_codes_enum RENAME TO iso_alpha_two_country_codes_enum;
  END IF;
END $$;

SELECT ax_define.bind_enum_table_to_table('code', 'episodes_licenses_countries', 'app_public', 'iso_alpha_two_country_codes');
SELECT ax_define.bind_enum_table_to_table('code', 'seasons_licenses_countries', 'app_public', 'iso_alpha_two_country_codes');
SELECT ax_define.bind_enum_table_to_table('code', 'tvshows_licenses_countries', 'app_public', 'iso_alpha_two_country_codes');
SELECT ax_define.bind_enum_table_to_table('code', 'movies_licenses_countries', 'app_public', 'iso_alpha_two_country_codes');
SELECT ax_define.set_enum_domain('code', 'episodes_licenses_countries', 'app_public', 'iso_alpha_two_country_codes_enum', 'app_public');
SELECT ax_define.set_enum_domain('code', 'seasons_licenses_countries', 'app_public', 'iso_alpha_two_country_codes_enum', 'app_public');
SELECT ax_define.set_enum_domain('code', 'tvshows_licenses_countries', 'app_public', 'iso_alpha_two_country_codes_enum', 'app_public');
SELECT ax_define.set_enum_domain('code', 'movies_licenses_countries', 'app_public', 'iso_alpha_two_country_codes_enum', 'app_public');

DROP FUNCTION IF EXISTS app_private.three_to_two_letter_country_code;
