apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-kv-media
spec:
  provider:
    azurekv:
      authSecretRef:
        clientId:
          key: ClientId
          name: azure-external-access-service-principal-credentials
        clientSecret:
          key: ClientSecret
          name: azure-external-access-service-principal-credentials
      authType: ServicePrincipal
      environmentType: PublicCloud
      tenantId: db0b4725-608f-4d84-b2e3-7fc15b0cb2d4
      vaultUrl: https://cus-cb-media-FLT.vault.azure.net
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: key-vault-media
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: SecretStore
    name: azure-kv-media
  target:
    name: key-vault-media
    creationPolicy: Owner
  data:
  - secretKey: database-name
    remoteRef:
      key: secret/postgres-service-database-name
  - secretKey: database-owner-password
    remoteRef:
      key: secret/postgres-owner-role-password
  - secretKey: database-owner-username
    remoteRef:
      key: secret/postgres-owner-role-name
  - secretKey: database-login-username
    remoteRef:
      key: secret/postgres-login-role-name
  - secretKey: database-login-password
    remoteRef:
      key: secret/postgres-login-role-password
  - secretKey: database-gql-username
    remoteRef:
      key: secret/postgres-gql-role-name
  - secretKey: rabbitmq-password
    remoteRef:
      key: secret/rabbitmq-password
  - secretKey: rabbitmq-user
    remoteRef:
      key: secret/rabbitmq-user
  - secretKey: service-account-client-secret
    remoteRef:
      key: secret/service-account-client-secret
  - secretKey: service-account-client-id
    remoteRef:
      key: secret/service-account-client-id
