apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  axinom.com/platform: mosaic
  mosaic.axinom.com/service: vod-to-live
commonLabels:
  axinom.com/platform: mosaic
  mosaic.axinom.com/service: vod-to-live
resources:
  - deployment.yaml
  - service.yaml
  - pod-monitor.yaml
  - http-route.yaml
