trigger: none
pr: none

pool:
  vmImage: ubuntu-latest
# TODO: rename file to backend-service-build and use single file for catalog, entitlement and media
variables:
  containerRegistry: harbor-beyonddutch-automation
  tag: $(Build.BuildNumber)

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - task: Docker@2
            displayName: Build Docker Image
            inputs:
              containerRegistry: $(containerRegistry)
              repository: beyonddutch-mosaic/$(imageRepo)
              command: build
              Dockerfile: Dockerfile
              buildContext: '.'
              tags: $(tag)
              arguments:
                '--build-arg PACKAGE_ROOT=$(packageRoot) --build-arg PACKAGE_BUILD_COMMAND=$(packageBuildCommand)'

          - task: Docker@2
            displayName: Push Docker Image to Axinom Container Registry
            inputs:
              containerRegistry: $(containerRegistry)
              repository: beyonddutch-mosaic/$(imageRepo)
              command: push
              tags: $(tag)

          - script: |
              echo "$(Build.BuildNumber)" > buildNumber.txt
            displayName: 'Write BuildNumber to file'

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: buildNumber.txt
              artifact: drop
            displayName: Publish BuildNumber value as an artifact