trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: nfn_acceptance
    displayName: Release to NFN acceptance
    type: boolean
    default: true
  - name: nfn_production
    displayName: Release to NFN production
    type: boolean
    default: false

variables:
  serviceId: 'dc-entitlement-service'
  containerRegistry: 'harbor-beyonddutch-automation'
  dockerfilePath: 'Dockerfile'
  packageRoot: 'services/entitlement/service'
  packageBuildCommand: 'build:entitlement-service:prod'
  imageRepository: 'beyonddutch-mosaic/mosaic-entitlement-service'
  tag: '$(Build.BuildNumber)'

  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - task: Cache@2
            inputs:
              key: 'yarn | "$(Agent.OS)" | yarn.lock'
              restoreKeys: |
                yarn | "$(Agent.OS)"
                yarn
              path: $(YARN_CACHE_FOLDER)
            displayName: Cache Yarn packages

          - task: Docker@2
            displayName: Build Docker Image
            inputs:
              containerRegistry: $(containerRegistry)
              repository: $(imageRepository)
              command: 'build'
              Dockerfile: $(dockerfilePath)
              buildContext: '.'
              tags: '$(tag)'
              arguments:
                '--build-arg PACKAGE_ROOT=$(packageRoot) --build-arg
                PACKAGE_BUILD_COMMAND=$(packageBuildCommand)'
          - task: Docker@2
            displayName: Push Docker Image to Axinom Container Registry
            inputs:
              containerRegistry: $(containerRegistry)
              repository: $(imageRepository)
              command: 'push'
              tags: '$(tag)'

      - job: Upload
        displayName: 'Upload Manifest to Acceptance'
        condition: ${{ eq(parameters.nfn_acceptance, true) }}
        variables:
          - group: vault-nfn-acceptance
        steps:
          - bash: |
              apt install -y jq
              echo "Temporarily switch to newer version of Mosaic CLI in package.json"
              jq '.devDependencies."@axinom/mosaic-cli"="0.20.0"' package.json > package.updated.json
              mv package.updated.json package.json
              yarn install
            displayName: 'Install Dev Dependencies'
          - task: Bash@3
            displayName: 'Upload deployment configuration to Acceptance environment'
            inputs:
              targetType: 'inline'
              script: |
                yarn mosaic hosting manifest upload -n "nfn-mosaic-entitlement-acceptance-$(tag)" -i "$(serviceId)" -p "$(packageRoot)"
            env:
              MOSAIC_HOSTING_CLIENT_ID: $(mosaicHostingClientIdAcc)
              MOSAIC_HOSTING_CLIENT_SECRET: $(mosaicHostingClientSecretAcc)
              ID_SERVICE_AUTH_BASE_URL: https://id.service.eu.axinom.net
              HOSTING_SERVICE_BASE_URL: https://hosting.service.eu.axinom.net
            secureVariables:
              GEOLITE2_LICENSE_KEY: $(GEOLITE2-LICENSE-KEY)
              DRM_LICENSE_COMMUNICATION_KEY: $(drm-com-key)
              DRM_LICENSE_COMMUNICATION_KEY_ID: $(drm-com-key-id)
              USER_SESSION_PUBLIC_KEY: $(session-public-key)
              RECURLY_ENTITLEMENT_PLAYBACK_PERMISSION: $(RECURLY-PLAYBACK-PERMISSION)
              RECURLY_ENTITLEMENT_API_KEY: $(RECURLY-API-KEY)
              GEOIP2_BLOB_SAS_TOKEN: $(GEOIP2-BLOB-SAS-TOKEN)

      - job: Upload
        displayName: 'Upload Manifest to Production'
        condition: ${{ eq(parameters.nfn_production, true) }}
        variables:
          - group: vault-nfn-production
        steps:
          - bash: |
              apt install -y jq
              echo "Temporarily switch to newer version of Mosaic CLI in package.json"
              jq '.devDependencies."@axinom/mosaic-cli"="0.20.0"' package.json > package.updated.json
              mv package.updated.json package.json
              yarn install
            displayName: 'Install Dev Dependencies' 
          - task: Bash@3
            displayName: 'Upload deployment configuration to Production environment'
            inputs:
              targetType: 'inline'
              script: |
                yarn mosaic hosting manifest upload -n "nfn-mosaic-entitlement-production-$(tag)" -i "$(serviceId)" -p "$(packageRoot)"
            env:
              MOSAIC_HOSTING_CLIENT_ID: $(mosaicHostingClientIdProd)
              MOSAIC_HOSTING_CLIENT_SECRET: $(mosaicHostingClientSecretProd)
              ID_SERVICE_AUTH_BASE_URL: https://id.service.eu.axinom.net
              HOSTING_SERVICE_BASE_URL: https://hosting.service.eu.axinom.net
            secureVariables:
              GEOLITE2_LICENSE_KEY: $(GEOLITE2-LICENSE-KEY)
              DRM_LICENSE_COMMUNICATION_KEY: $(drm-com-key)
              DRM_LICENSE_COMMUNICATION_KEY_ID: $(drm-com-key-id)
              USER_SESSION_PUBLIC_KEY: $(session-public-key)
              RECURLY_ENTITLEMENT_PLAYBACK_PERMISSION: $(RECURLY-PLAYBACK-PERMISSION)
              RECURLY_ENTITLEMENT_API_KEY: $(RECURLY-API-KEY)
              GEOIP2_BLOB_SAS_TOKEN: $(GEOIP2-BLOB-SAS-TOKEN)
