trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  tag: '$(Build.BuildNumber)'
  serviceId: dc-media-service
  ID_SERVICE_AUTH_BASE_URL: https://id.service.eu.axinom.net

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: |
              ORIGINAL_PKG_VER=`npx -q json -f "$(packageRoot)/package.json" version`
              NEW_PKG_VER="${ORIGINAL_PKG_VER}-$(tag)"
              echo "##vso[task.setvariable variable=pkgVer]${NEW_PKG_VER}"

              echo "Current package.json version is: [${ORIGINAL_PKG_VER}]"
              echo "Updating package.json version to: [${NEW_PKG_VER}]"
              
              npx -q json -I -f "$(packageRoot)/package.json" -e "this.version = '${NEW_PKG_VER}'"
              
              echo "Updated package.json version is: [`npx -q json -f \"$(packageRoot)/package.json\" version`]"
            displayName:
              'Updating package.json version to reflect the build number'

          - script: |
              npm run $(packageBuildCommand)
            displayName: 'Build pilet'

          - task: CopyFiles@2
            inputs:
              Contents: '*.tgz'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
            displayName: Copy pilet package artifact to staging directory

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
            displayName: Publishing build artifact
          
          - task: Bash@3
            displayName:
              'Upload pilet to INT environment'
            inputs:
              targetType: 'inline'
              script: |
                yarn mosaic hosting pilet register -i "$(serviceId)" -p "$(Build.ArtifactStagingDirectory)/media-workflows-$(pkgVer).tgz" -m "https://frontends.service.eu.axinom.net"
            env:
              MOSAIC_HOSTING_CLIENT_ID: $(mosaicHostingClientIdInt)
              MOSAIC_HOSTING_CLIENT_SECRET: $(mosaicHostingClientSecretInt)

          - task: Bash@3
            displayName:
              'Upload pilet to PERF environment'
            inputs:
              targetType: 'inline'
              script: |
                yarn mosaic hosting pilet register -i "$(serviceId)" -p "$(Build.ArtifactStagingDirectory)/media-workflows-$(pkgVer).tgz" -m "https://frontends.service.eu.axinom.net"
            env:
              MOSAIC_HOSTING_CLIENT_ID: $(mosaicHostingClientIdPerf)
              MOSAIC_HOSTING_CLIENT_SECRET: $(mosaicHostingClientSecretPerf)

          - task: Bash@3
            displayName:
              'Upload pilet to NFN acceptance environment'
            inputs:
              targetType: 'inline'
              script: |
                yarn mosaic hosting pilet register -i "$(serviceId)" -p "$(Build.ArtifactStagingDirectory)/media-workflows-$(pkgVer).tgz" -m "https://frontends.service.eu.axinom.net"
            env:
              MOSAIC_HOSTING_CLIENT_ID: $(mosaicHostingClientIdNfnAcc)
              MOSAIC_HOSTING_CLIENT_SECRET: $(mosaicHostingClientSecretNfnAcc)

          - task: Bash@3
            displayName:
              'Upload pilet to NFN migration environment'
            inputs:
              targetType: 'inline'
              script: |
                yarn mosaic hosting pilet register -i "$(serviceId)" -p "$(Build.ArtifactStagingDirectory)/media-workflows-$(pkgVer).tgz" -m "https://frontends.service.eu.axinom.net"
            env:
              MOSAIC_HOSTING_CLIENT_ID: $(mosaicHostingClientIdNfnMigration)
              MOSAIC_HOSTING_CLIENT_SECRET: $(mosaicHostingClientSecretNfnMigration)

          - task: Bash@3
            displayName:
              'Upload pilet to NFN production environment'
            inputs:
              targetType: 'inline'
              script: |
                yarn mosaic hosting pilet register -i "$(serviceId)" -p "$(Build.ArtifactStagingDirectory)/media-workflows-$(pkgVer).tgz" -m "https://frontends.service.eu.axinom.net"
            env:
              MOSAIC_HOSTING_CLIENT_ID: $(mosaicHostingClientIdNfnProd)
              MOSAIC_HOSTING_CLIENT_SECRET: $(mosaicHostingClientSecretNfnProd)

          - task: Bash@3
            displayName:
              'Upload pilet to LOV acceptance environment'
            inputs:
              targetType: 'inline'
              script: |
                yarn mosaic hosting pilet register -i "$(serviceId)" -p "$(Build.ArtifactStagingDirectory)/media-workflows-$(pkgVer).tgz" -m "https://frontends.service.eu.axinom.net"
            env:
              MOSAIC_HOSTING_CLIENT_ID: $(mosaicHostingClientIdLovAcc)
              MOSAIC_HOSTING_CLIENT_SECRET: $(mosaicHostingClientSecretLovAcc)
            
          - task: Bash@3
            displayName:
              'Upload pilet to LOV migration environment'
            inputs:
              targetType: 'inline'
              script: |
                yarn mosaic hosting pilet register -i "$(serviceId)" -p "$(Build.ArtifactStagingDirectory)/media-workflows-$(pkgVer).tgz" -m "https://frontends.service.eu.axinom.net"
            env:
              MOSAIC_HOSTING_CLIENT_ID: $(mosaicHostingClientIdLovMigration)
              MOSAIC_HOSTING_CLIENT_SECRET: $(mosaicHostingClientSecretLovMigration)

          - task: Bash@3
            displayName:
              'Upload pilet to LOV production environment'
            inputs:
              targetType: 'inline'
              script: |
                yarn mosaic hosting pilet register -i "$(serviceId)" -p "$(Build.ArtifactStagingDirectory)/media-workflows-$(pkgVer).tgz" -m "https://frontends.service.eu.axinom.net"
            env:
              MOSAIC_HOSTING_CLIENT_ID: $(mosaicHostingClientIdLovProd)
              MOSAIC_HOSTING_CLIENT_SECRET: $(mosaicHostingClientSecretLovProd)