trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: build
    displayName: Build
    type: boolean
    default: true
  - name: int
    displayName: Release manifest to INT
    type: boolean
    default: true
  - name: nfn_acceptance
    displayName: Release manifest to NFN acceptance
    type: boolean
    default: false
  - name: nfn_production
    displayName: Release manifest to NFN production
    type: boolean
    default: false
  - name: lov_acceptance
    displayName: Release manifest to LOV acceptance
    type: boolean
    default: false
  - name: lov_production
    displayName: Release manifest to LOV production
    type: boolean
    default: false

variables:
  serviceId: dc-media-service
  containerRegistry: 'harbor-beyonddutch-automation'
  dockerfilePath: 'Dockerfile'
  packageRoot: 'services/media/service'
  packageBuildCommand: 'build:media-service:prod'
  imageRepository: 'beyonddutch-mosaic/mosaic-media-service'
  tag: '$(Build.BuildNumber)'
  ID_SERVICE_AUTH_BASE_URL: https://id.service.eu.axinom.net
  HOSTING_SERVICE_BASE_URL: https://hosting.service.eu.axinom.net
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build
        condition: ${{ eq(parameters.build, true) }}
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - task: Cache@2
            inputs:
              key: 'yarn | "$(Agent.OS)" | yarn.lock'
              restoreKeys: |
                yarn | "$(Agent.OS)"
                yarn
              path: $(YARN_CACHE_FOLDER)
            displayName: Cache Yarn packages

          - task: Docker@2
            displayName: Build Docker Image
            inputs:
              containerRegistry: $(containerRegistry)
              repository: $(imageRepository)
              command: 'build'
              Dockerfile: $(dockerfilePath)
              buildContext: '.'
              tags: '$(tag)'
              arguments:
                '--build-arg PACKAGE_ROOT=$(packageRoot) --build-arg
                PACKAGE_BUILD_COMMAND=$(packageBuildCommand)'

          - task: Bash@3
            displayName:
              'Install Dev Dependencies'
            inputs:
              targetType: 'inline'
              script: |
                apt install -y jq
                echo "Temporarily switch to newer version of Mosaic CLI in package.json"
                jq '.devDependencies."@axinom/mosaic-cli"="0.20.0"' package.json > package.updated.json
                mv package.updated.json package.json
                yarn install

          - task: Docker@2
            displayName: Push Docker Image to Axinom Container Registry
            inputs:
              containerRegistry: $(containerRegistry)
              repository: $(imageRepository)
              command: 'push'
              tags: '$(tag)'

      - job: Release_INT
        dependsOn: Build
        displayName: 'Release to INT'
        condition: ${{ eq(parameters.int, true) }}
        variables:
          - group: vault-int
        steps:
          - bash: |
              apt install -y jq
              echo "Temporarily switch to newer version of Mosaic CLI in package.json"
              jq '.devDependencies."@axinom/mosaic-cli"="0.20.0"' package.json > package.updated.json
              mv package.updated.json package.json
              yarn install
            displayName: 'Install Dev Dependencies'
          - task: qetza.replacetokens.replacetokens-task.replacetokens@6
            displayName: 'Replace tokens'
            inputs:
              sources: '$(packageRoot)/mosaic-hosting-deployment-manifest.yaml'
              caseInsensitivePaths: false
              includeDotPaths: false
              missingVarAction: keep
              missingVarLog: error
              ifNoFilesFound: error
          - task: Bash@3
            displayName:
              'Upload manifest'
            inputs:
              targetType: 'inline'
              script: |
                yarn mosaic hosting manifest upload -n "mosaic-media-int-$(tag)" -i "$(serviceId)" -p "$(packageRoot)"
            env:
              MOSAIC_HOSTING_CLIENT_ID: $(mosaicHostingClientIdInt)
              MOSAIC_HOSTING_CLIENT_SECRET: $(mosaicHostingClientSecretInt)
          # - task: Bash@3
          #   displayName:
          #     'Deploy Mosaic service'
          #   inputs:
          #     targetType: 'inline'
          #     script: |
          #       # workflows are deployed separately onto each env, thus we can't assume latest runID was for needed env
          #       # -p media-workflows@1.0.0-$(resources.pipeline.media-workflow.runID)
                
          #       yarn mosaic hosting service deploy -i "$(serviceId)" -t $(tag) -m mosaic-media-int-$(tag) -n "media-service-$(tag)"
          #   env:
          #     MOSAIC_HOSTING_CLIENT_ID: $(mosaicHostingClientIdInt)
          #     MOSAIC_HOSTING_CLIENT_SECRET: $(mosaicHostingClientSecretInt)

      - job: Upload_NFN_Acceptance
        dependsOn: Build
        displayName: 'Upload Manifest to NFN Acceptance'
        condition: ${{ eq(parameters.nfn_acceptance, true) }}
        variables:
          - group: vault-nfn-acceptance
        steps:
          - bash: |
              apt install -y jq
              echo "Temporarily switch to newer version of Mosaic CLI in package.json"
              jq '.devDependencies."@axinom/mosaic-cli"="0.20.0"' package.json > package.updated.json
              mv package.updated.json package.json
              yarn install
            displayName: 'Install Dev Dependencies'
          - task: qetza.replacetokens.replacetokens-task.replacetokens@6
            displayName: 'Replace tokens'
            inputs:
              sources: '$(packageRoot)/mosaic-hosting-deployment-manifest.yaml'
              caseInsensitivePaths: false
              includeDotPaths: false
              missingVarAction: keep
              missingVarLog: error
              ifNoFilesFound: error
          - task: Bash@3
            displayName:
              'Upload deployment configuration to NFN Acceptance environment'
            inputs:
              targetType: 'inline'
              script: |
                yarn mosaic hosting manifest upload -n "nfn-mosaic-media-acceptance-$(tag)" -i "$(serviceId)" -p "$(packageRoot)"
            env:
              MOSAIC_HOSTING_CLIENT_ID: $(mosaicHostingClientIdNfnAcc)
              MOSAIC_HOSTING_CLIENT_SECRET: $(mosaicHostingClientSecretNfnAcc)

      - job: Upload_NFN_Production
        dependsOn: Build
        displayName: 'Upload Manifest to NFN Production'
        condition: ${{ eq(parameters.nfn_production, true) }}
        variables:
          - group: vault-nfn-production
        steps:
          - bash: |
              apt install -y jq
              echo "Temporarily switch to newer version of Mosaic CLI in package.json"
              jq '.devDependencies."@axinom/mosaic-cli"="0.20.0"' package.json > package.updated.json
              mv package.updated.json package.json
              yarn install
            displayName: 'Install Dev Dependencies'
          - task: qetza.replacetokens.replacetokens-task.replacetokens@6
            displayName: 'Replace tokens'
            inputs:
              sources: '$(packageRoot)/mosaic-hosting-deployment-manifest.yaml'
              caseInsensitivePaths: false
              includeDotPaths: false
              missingVarAction: keep
              missingVarLog: error
              ifNoFilesFound: error
          - task: Bash@3
            displayName:
              'Upload deployment configuration to NFN Production environment'
            inputs:
              targetType: 'inline'
              script: |
                yarn mosaic hosting manifest upload -n "nfn-mosaic-media-production-$(tag)" -i "$(serviceId)" -p "$(packageRoot)"
            env:
              MOSAIC_HOSTING_CLIENT_ID: $(mosaicHostingClientIdNfnProd)
              MOSAIC_HOSTING_CLIENT_SECRET: $(mosaicHostingClientSecretNfnProd)

      - job: Upload_LOV_Acceptance
        dependsOn: Build
        displayName: 'Upload Manifest to LOV Acceptance'
        condition: ${{ eq(parameters.lov_acceptance, true) }}
        variables:
          - group: vault-lov-acceptance
        steps:
          - bash: |
              apt install -y jq
              echo "Temporarily switch to newer version of Mosaic CLI in package.json"
              jq '.devDependencies."@axinom/mosaic-cli"="0.20.0"' package.json > package.updated.json
              mv package.updated.json package.json
              yarn install
            displayName: 'Install Dev Dependencies'
          - task: qetza.replacetokens.replacetokens-task.replacetokens@6
            displayName: 'Replace tokens'
            inputs:
              sources: '$(packageRoot)/mosaic-hosting-deployment-manifest.yaml'
              caseInsensitivePaths: false
              includeDotPaths: false
              missingVarAction: keep
              missingVarLog: error
              ifNoFilesFound: error
          - task: Bash@3
            displayName:
              'Upload deployment configuration to LOV Acceptance environment'
            inputs:
              targetType: 'inline'
              script: |
                yarn mosaic hosting manifest upload -n "lov-mosaic-media-acceptance-$(tag)" -i "$(serviceId)" -p "$(packageRoot)"
            env:
              MOSAIC_HOSTING_CLIENT_ID: $(mosaicHostingClientIdLovAcc)
              MOSAIC_HOSTING_CLIENT_SECRET: $(mosaicHostingClientSecretLovAcc)

      - job: Upload_LOV_Production
        dependsOn: Build
        displayName: 'Upload Manifest to LOV Production'
        condition: ${{ eq(parameters.lov_production, true) }}
        variables:
          - group: vault-lov-production
        steps:
          - bash: |
              apt install -y jq
              echo "Temporarily switch to newer version of Mosaic CLI in package.json"
              jq '.devDependencies."@axinom/mosaic-cli"="0.20.0"' package.json > package.updated.json
              mv package.updated.json package.json
              yarn install
            displayName: 'Install Dev Dependencies'
          - task: qetza.replacetokens.replacetokens-task.replacetokens@6
            displayName: 'Replace tokens'
            inputs:
              sources: '$(packageRoot)/mosaic-hosting-deployment-manifest.yaml'
              caseInsensitivePaths: false
              includeDotPaths: false
              missingVarAction: keep
              missingVarLog: error
              ifNoFilesFound: error
          - task: Bash@3
            displayName:
              'Upload deployment configuration to LOV Production environment'
            inputs:
              targetType: 'inline'
              script: |
                yarn mosaic hosting manifest upload -n "lov-mosaic-media-production-$(tag)" -i "$(serviceId)" -p "$(packageRoot)"
            env:
              MOSAIC_HOSTING_CLIENT_ID: $(mosaicHostingClientIdLovProd)
              MOSAIC_HOSTING_CLIENT_SECRET: $(mosaicHostingClientSecretLovProd)