query AgeRatings {
  ageRatings(orderBy: NAME_ASC) {
    nodes {
      id
      name
      createdDate
      createdUser
      updatedDate
      updatedUser
    }
    totalCount
  }
}

mutation CreateAgeRating($input: CreateAgeRatingInput!) {
  createAgeRating(input: $input) {
    ageRating {
      id
      name
    }
  }
}

mutation UpdateAgeRating($input: UpdateAgeRatingInput!) {
  updateAgeRating(input: $input) {
    ageRating {
      id
      name
    }
  }
}

mutation DeleteAgeRating($input: DeleteAgeRatingInput!) {
  deleteAgeRating(input: $input) {
    ageRating {
      id
      name
    }
  }
}
