export const Constants = {
  // Entity Types
  MOVIE: 'Movie',
  MOVIE_GENRE: 'Movie Genre',
  TVSHOW: 'TV Show',
  TVSHOW_GENRE: 'TV Show Genre',
  SEASON: 'Season',
  EPISODE: 'Episode',
  COLLECTION: 'Collection',

  // Publish Status
  NOT_PUBLISHED: 'Not Published',
  PUBLISHED: 'Published',
  CHANGED: 'Changed',

  // Snapshot State
  INITIALIZATION: 'Initialization',
  VALIDATION: 'Validation',
  INVALID: 'Invalid',
  READY: 'Ready',
  SCHEDULED: 'Scheduled',
  UNPUBLISHED: 'Unpublished',
  VERSION_MISMATCH: 'Version Mismatch',
  ERROR: 'Error',

  //Ingest Status
  IN_PROGRESS: 'In Progress',
  SUCCESS: 'Success',
  PARTIAL_SUCCESS: 'Partial Success',

  //Business Types
  ADVERTISEMENT: 'Advertisement',
  ADVERTISEMENT_AUTHENTICATED: 'Advertisement Authenticated',
  ADVERTISEMENT_DOWNLOADABLE: 'Advertisement Downloadable',
  FREE: 'Free',
  FREE_AUTHENTICATED: 'Free Authenticated',
  FREE_DOWNLOADABLE: 'Free Downloadable',
  PREMIUM: 'Premium',
  PREMIUM_DOWNLOADABLE: 'Premium Downloadable',

  //Asset SubTypes
  ALBUM: 'Album',
  AUDIO_TRACK: 'Audio Track',
  CONTENT_SET: 'Content set',
  CUSTOM: 'Custom',
  FILE: 'File',
  PROMOTION: 'Promotion',
  SUBSCRIPTION_PLAN: 'Subscription plan',
  TV_SHOW: 'TV Show',
  UNKNOWN: 'Unknown',

  //Image types
  MOVIE_COVER: 'Cover',
  MOVIE_COVER_1X1: 'Cover 1x1',
  MOVIE_COVER_16X9: 'Cover 16x9',
  MOVIE_CLEAN_COVER: 'Clean Cover',
  MOVIE_CLEAN_COVER_1X1: 'Clean Cover 1x1',
  MOVIE_CLEAN_COVER_16X9: 'Clean Cover 16x9',
  MOVIE_LIST: 'List',
  MOVIE_LIST_1X1: 'List 1x1',
  MOVIE_LIST_9X13: 'List 9x13',

  TVSHOW_COVER: 'Cover',
  TVSHOW_COVER_1X1: 'Cover 1x1',
  TVSHOW_COVER_16X9: 'Cover 16x9',
  TVSHOW_CLEAN_COVER: 'Clean Cover',
  TVSHOW_CLEAN_COVER_1X1: 'Clean Cover 1x1',
  TVSHOW_CLEAN_COVER_16X9: 'Clean Cover 16x9',
  TVSHOW_LIST: 'List',
  TVSHOW_LIST_1X1: 'List 1x1',
  TVSHOW_LIST_9X13: 'List 9x13',

  SEASON_COVER: 'Cover',
  SEASON_COVER_1X1: 'Cover 1x1',
  SEASON_COVER_16X9: 'Cover 16x9',
  SEASON_CLEAN_COVER: 'Clean Cover',
  SEASON_CLEAN_COVER_1X1: 'Clean Cover 1x1',
  SEASON_CLEAN_COVER_16X9: 'Clean Cover 16x9',
  SEASON_LIST: 'List',
  SEASON_LIST_1X1: 'List 1x1',
  SEASON_LIST_9X13: 'List 9x13',

  EPISODE_COVER: 'Cover',
  EPISODE_COVER_1X1: 'Cover 1x1',
  EPISODE_COVER_16X9: 'Cover 16x9',
  EPISODE_CLEAN_COVER: 'Clean Cover',
  EPISODE_CLEAN_COVER_1X1: 'Clean Cover 1x1',
  EPISODE_CLEAN_COVER_16X9: 'Clean Cover 16x9',
  EPISODE_LIST: 'List',
  EPISODE_LIST_1X1: 'List 1x1',
  EPISODE_LIST_9X13: 'List 9x13',

  COLLECTION_COVER: 'Cover',
  COLLECTION_COVER_1X1: 'Cover 1x1',
  COLLECTION_COVER_4X1: 'Cover 4x1',
  COLLECTION_CLEAN_COVER: 'Clean Cover',
  COLLECTION_CLEAN_COVER_1X1: 'Clean Cover 1x1',
  COLLECTION_CLEAN_COVER_4X1: 'Clean Cover 4x1',
  COLLECTION_LIST: 'List',
  COLLECTION_LIST_1X1: 'List 1x1',
  COLLECTION_LIST_15X16: 'List 15x16',
};
