query CollectionRelatedEntities($id: Int!) {
  collection(id: $id) {
    collectionRelations(orderBy: SORT_ORDER_ASC) {
      nodes {
        movie {
          entityId: id
          title
          publishStatus
          entityImages: moviesImages {
            nodes {
              imageId
            }
          }
          entityLicenses: moviesLicenses {
            nodes {
              licenseEnd
            }
          }
        }

        tvshow {
          entityId: id
          title
          publishStatus
          entityImages: tvshowsImages {
            nodes {
              imageId
            }
          }
          entityLicenses: tvshowsLicenses {
            nodes {
              licenseEnd
            }
          }
        }

        episode {
          entityId: id
          title
          publishStatus
          entityImages: episodesImages {
            nodes {
              imageId
            }
          }
          entityLicenses: episodesLicenses {
            nodes {
              licenseEnd
            }
          }
        }

        childCollection {
          entityId: id
          title
          publishStatus
          entityImages: collectionsImages {
            nodes {
              imageId
            }
          }
        }

        id
        sortOrder
      }
    }
  }
}
